### ISSUE TITLE
Unable to set a field to 'null'

### ISSUE THREAD

**Issue by yofang** [Jericho/StrongGrid#104]
I create a campaign using Client.Campaigns.CreateAsync(), where i set suppressionGroupId=xxx and customUnsubscribeUrl=null.
Then, I regret. I want to update the campaign to use my custom unsubscribe url.
So I tried to call Client.Campaigns.UpdateAsync(), with suppressionGroupId=null and customUnsubscribeUrl=yyy.
SendGrid Api responded an error, saying I should only applied one of { suppressionGroupId, customUnsubscribeUrl }.

**Comment by Jericho** [comment]
This is an interesting situation you are describing. Currently, the logic in update methods is to ignore parameters that contain a null value (the thinking is that you pass a null value when you want a given field to remain untouched) but in your case you want to specifically set a field to a null value. 

I need to do some thinking to figure out how to allow you you to set a field to a null value. Suggestions are welcome.

**Comment by yofang** [comment]
One possible fix is to make type of parameters nullable string. Then null means to ignore, an empty string means to delete.

**Comment by Jericho** [comment]
Currently, you can pass `null` as a parameter to a method such as `Campaigns.UpdateSync` for example to indicate that the value of the corresponding field should remain unchanged. In fact, most parameters to methods like `UpdateSync` are optional which means that you can omit them and a `null` value will be implied. This works well for most cases except for one specific scenario: you can't deliberately set a field to `null`.

The change introduced in release 0.21.0 will solve this scenario. You will still be able to omit parameters which will leave their corresponding field untouched, but you will also be able to specify a `null` value to clear the content of the field.
