### ISSUE TITLE
Issue with client.InvalidEmails.GetAsync(email);

### ISSUE THREAD

**Issue by lukemills01** [Jericho/StrongGrid#106]
Calling this fails because the object being returned appears to be an array

**Comment by Jericho** [comment]
I double checked [SendGrid's documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/invalid_emails.html) and the `Get` does indeed return an array. 

I'll fix and publish a new release shortly.

**Comment by Jericho** [comment]
Release 0.18.0 was published with a fix for this issue. Thanks for reporting it.
