### ISSUE TITLE
Nuget Package Issue with VS2013

### ISSUE THREAD

**Issue by nitro52** [Jericho/StrongGrid#109]
I would love to be able to use this but when i try to install the nuget package in VS2013 i get the message

The 'System.Net.Http 4.0.0' package requires NuGet client version '3.0' or above, but the current NuGet version is '2.12.0.817'.

The upgrade nuget button just takes you to Visual Studio's Extensions & Updates tool but the nuget package manger for visual studio appears to be on the latest version. 

Anyone had this problem?

**Comment by Jericho** [comment]
There's a StackOverflow [discussion about this issue](http://stackoverflow.com/questions/32776772/how-to-use-nuget-3-0-with-visual-studio-2013). Maybe it can help?

Other than that, the only thing I can suggest is to upgrade to Visual Studio 2015. There is a free community edition [available for download](https://www.visualstudio.com/vs/community/) (that's what I use).

**Comment by nitro52** [comment]
I'll check that out again on Monday. I don't remember seeing any System.Collections.Immutable packages though.

VS2015 community is not really an option at this time. Its for a corporate project.

**Comment by nitro52** [comment]
Hi Jeicho,
So i don't think it relates to another package i installed rather a dependency that StrongGrid has on System.Net.Http 4.0.0.

If you check their nuget page it does say requires 3.0. https://www.nuget.org/packages/System.Net.Http/4.0.0

From what i can find 3.0 seems to be for .net core 5 which 2013 does not support. this might be why it won't update. I also found this on the nuget github page https://github.com/NuGet/Home/issues/2093

It would be nice to use nuget but it guess its not required. Is there any reason you need System.Net.Http 4.0.0 though? could you update the dependancy to use a previous version that does not depend on .net core? Or would it make a bunch of breaking changes?

**Comment by Jericho** [comment]
I don't have access to Visual Studio 2013 so I won't be able to test, but I created a version of the nuget package that references an older version of System.Net.Http and published it on MyGet: https://www.myget.org/feed/jericho/package/nuget/StrongGrid

Let me know if it works.

**Comment by nitro52** [comment]
I added your feed to nuget package manager in visual studio 2013 and then installed the 0.19.0-alpha0156 version. Looks like that fixed the problem. I can see its using 2.0 of System.Net.Http now

> PM> Install-Package StrongGrid -Version 0.19.0-alpha0156
Attempting to resolve dependency 'HttpMultipartParser (≥ 2.2.0)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 9.0.1)'.
Attempting to resolve dependency 'System.Net.Http (≥ 2.0.20710)'.
Installing 'HttpMultipartParser 2.2.0'.
Successfully installed 'HttpMultipartParser 2.2.0'.
Installing 'StrongGrid 0.19.0-alpha0156'.
Successfully installed 'StrongGrid 0.19.0-alpha0156'.
Adding 'HttpMultipartParser 2.2.0' to QuickflixWebServices.
Successfully added 'HttpMultipartParser 2.2.0' to QuickflixWebServices.
Adding 'Newtonsoft.Json 9.0.1' to QuickflixWebServices.
Successfully added 'Newtonsoft.Json 9.0.1' to QuickflixWebServices.
Adding 'Microsoft.Net.Http 2.0.20710.0' to QuickflixWebServices.
Successfully added 'Microsoft.Net.Http 2.0.20710.0' to QuickflixWebServices.
Adding 'System.Net.Http 2.0.20710.0' to QuickflixWebServices.
Installing 'System.Net.Http 2.0.20710.0'.
You are downloading System.Net.Http from Microsoft, the license agreement to which is available at http://www.microsoft.com/web/webpi/eula/MVC_4_eula_ENU.htm. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'System.Net.Http 2.0.20710.0'.
Successfully added 'System.Net.Http 2.0.20710.0' to QuickflixWebServices.
Adding 'StrongGrid 0.19.0-alpha0156' to QuickflixWebServices.
Successfully added 'StrongGrid 0.19.0-alpha0156' to QuickflixWebServices.

**Comment by Jericho** [comment]
Just a heads up: in the upcoming release of the StrongGrid library, I will switch from System.Net.Http to a nuget package called FluentHttpClient which references System.Net.Http version 4. I contacted the project maintainer and he doesn't plan on supporting Visual Studio 2013. This means that you should continue using the alpha build I previously created for you for as long as you use VS.NET 2013.
