### ISSUE TITLE
Needs to throw appropriate exception when api key is wrong

### ISSUE THREAD

**Issue by ahnseunghae** [Jericho/StrongGrid#110]
I spent some time to figure it out that StrongGrid throws an exception when trying to send email.
It turns out I put wrong api key. ( simple mistake )
So I think It would be nice if appropriate exception is thrown when api key is wrong

**Comment by Jericho** [comment]
When I use an invalid API key, the SendGrid API returns the following Json: `{"errors":[{"field":null,"message":"authorization required"}]}` and the StrongGrid library throws an exception.

Is that not what you experience?

**Comment by ahnseunghae** [comment]
I am using StrongGrid 0.18.0
When I try to send message, I got the exceptions 
```
Exception thrown: 'System.Exception' in StrongGrid.dll
Exception thrown: 'System.AggregateException' in System.Private.CoreLib.ni.dll
```
with that exception messages, I don't know what is wrong.

Here is the method I am trying to use.

```
public async Task SendEmailAsync(EmailMessage model)
{
    var client = new Client(_apiKey);
    var from = new MailAddress(model.From, "");
            
    var tos = new List<MailAddress>();
    foreach (var to in model.To)
    {
        tos.Add(new MailAddress(to, ""));
    }
    var textContent = new MailContent("text/plain", model.TextBody);
    var htmlContent = new MailContent("text/html", model.HtmlBody);

    var personalizations = new []
    {
        new MailPersonalization
        {
            To = tos.ToArray(),
            Substitutions = model.Substitutions.ToArray(),
        }
    };

    client.Mail.SendAsync(
        personalizations, 
        model.Subject,
        new[] { textContent, htmlContent }, 
        from,
        templateId: model.TemplateId
    ).Wait();
}
```

**Comment by Jericho** [comment]
I notice that you are not awaiting the call to 'SendAsync' which seems odd to me but other than that, your code looks fine. Are you able to show the JSON returned from the SendGrid API?

**Comment by Jericho** [comment]
One more question, what is the message of the exception?

**Comment by Jericho** [comment]
Without any additional info, I'm afraid I'm not going to be able to help you so I'm closing this issue.
