### ISSUE TITLE
Send email with template example

### ISSUE THREAD

**Issue by fa10** [Jericho/StrongGrid#111]
Hi @Jericho,

Can you provide a example that shows how to send a email with a template to a single user?

Thanks!

**Comment by Jericho** [comment]
The `SendToSingleRecipientAsync` method has a parameter called `templateId`. You simply need to pass the unique identifier of your desired template (along with all other parameters that SendGrid requires).

**Comment by fa10** [comment]
Thanks for the answer, but what about substitutions in this mail ?

**Comment by Jericho** [comment]
`SendToSingleRecipientAsync` and `SendToMultipleRecipientsAsync` are simply convenience methods that address the most common scenarios. If you need more flexibility, you should use `SendAsync` which allows you to specify all the parameters accepted by SendGrid, which includes `MailPersonalization`.

**Comment by Jericho** [comment]
I hope I was able to answer your question. I'm closing this issue for now but feel free to post any follow up questions.

**Comment by fa10** [comment]
@Jericho thanks for the answers! I have one question more what about the <%body%> in the template how do i get that "replaced" is it not the MailContent i have to set?

**Comment by Jericho** [comment]
As far as I know, yes. From SendGrid's documentation:

> The text property is substituted into the <%body%> of the text template and html is substituted into the <%body%> of the HTML template. If the text property is present, but not html, then the resulting email will only contain the text version of the template, not the HTML version. The <%subject%> property is used for both Text and HTML templates.
