### ISSUE TITLE
Remove packages that prevent the webhook parser from being used in NETFULL

### ISSUE THREAD

**Issue by jasneo** [Jericho/StrongGrid#112]
The json parameter is a valid json object from SendGrid API.

I am using MVC 5 application. Visual Studio complains that `ParseWebhookEventsAsync` requires Microsoft.AspNetCore.Http.Abstractions which is in ASP.NET Core that I am not using.

`Error : The type 'HttpRequest' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`

```
            var parser = new WebhookParser();
            var stream = new MemoryStream();
            var writer = new StreamWriter(stream);
            writer.Write(json);
            writer.Flush();
            stream.Position = 0;
            var events = parser.ParseWebhookEventsAsync(stream).ConfigureAwait(false);
```

**Comment by Jericho** [comment]
As you point out, looks like 'Microsoft.AspNetCore.Http.Abstractions' assumes .NET Core is available even when it's not. Let me investigate and try to find a solution.

**Comment by Jericho** [comment]
I published a solution to the [MyGet feed](https://www.myget.org/feed/jericho/package/nuget/StrongGrid). It's version 0.18.1 Beta0001 (ignore 0.19.0 Alpha). Let me know if this works and if so, I'll publish to NuGet.

**Comment by jasneo** [comment]
@Jericho The solution looks good. I am getting another error asking me to add a reference for System.Web.

The error is `The type 'HttpRequest' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`.

It will be good if we can also do away with System.Web reference as I am using only the `Stream`.

**Comment by Jericho** [comment]
ok, let's try a different approach: the reason why there is a reference to `Microsoft.AspNetCore.Http.Abstractions` (.net standard) and `System.Web` (.net full), is because is this overload for the ParseWebhookEventsAsync method (notice the HttpRequest parameter):
```CSharp
public Task<Event[]> ParseWebhookEventsAsync(HttpRequest httpRequest)
```
There is a similar overload for the public ParseInboundEmailWebhook method (again, notice the HttpRequest parameter):
```CSharp
public InboundEmail ParseInboundEmailWebhook(HttpRequest httpRequest)
```

Do you think it would be reasonable to remove this overload completely, and developers would be responsible for converting the incoming request into a stream?

If so, could you give me a sample MVC controller that I could paste into the ReadMe to demonstrate how to do this?

**Comment by jasneo** [comment]
In my opinion, it's better to remove the overload for `HttpRequest` and change the `ParseWebhookEventsAsync` to accept string as parameter and have it return Json object as I am working on a complex system using N-tiered architecture and have to pass the string across the services. I don't think it's possible to pass the stream across the services.

Hence, it should be the onus on developers to parse the `HttpRequest` to the string.

Sample code for MVC controller and parser function.

```
        public JsonResult ReceiveEvents()
        {
            var req = Request.InputStream;
            var json = new StreamReader(req).ReadToEnd();
            ... call ParseBroadcastEvents function in different service ...
            _serviceProxy.Call(s => s.ParseBroadcastEvents(json));
            return Json(null);
        }

        public void ParseBroadcastEvents(string json)
        {
            File.WriteAllText($"D:\\Logs\\broadcastevent_{DateTime.Now:yyyyMMddHHmmss}.txt", json);

            var parser = new WebhookParser();
            var stream = new MemoryStream();
            var writer = new StreamWriter(stream);
            writer.Write(json);
            writer.Flush();
            stream.Position = 0;
            var events = parser.ParseWebhookEventsAsync(stream).ConfigureAwait(false);
            // The above several lines can be condensed into one line if we can pass the string to ParseWebhookEvents function.
            // var events = parser.ParseWebhookEventsAsync(json).ConfigureAwait(false);
        }
```

**Comment by Jericho** [comment]
Ok pushed a new beta to MyGet (0.18.1-beta0008):

- Removed reference to Microsoft.AspNetCore.Http.Abstractions
- Removed reference to System.Web
- Removed ParseWebhookEventsAsync overload accepting a HttpRequest parameter
- Added ParseWebhookEvents accepting a string

**Comment by Jericho** [comment]
Releasing hotfix 0.18.1
