### ISSUE TITLE
Event Property "sg_user_id" (Webhooks) 

### ISSUE THREAD

**Issue by lsshenrique** [Jericho/StrongGrid#116]
I contacted SendGrid's support for the UserID property, so they confirmed that the UserID property (sg_user_id) is only included in events sent from the marketing campaigns plataform. That is, all events from the marketing campaigns (click, open, bounce and others) have the property UserID.

Now, what is more correct to do? Does create the property in the event class or include as a unique argument? Because, depending on the event, I don't have access to this property after deserialize json.

**Comment by Jericho** [comment]
Can you show me a few examples of the JSON you are receiving from SendGrid?

**Comment by lsshenrique** [comment]
Yes, below are some examples of the JSON sent by SendGrid.

`[  
   {  
      "ip":"167.89.10.181",
      "sg_user_id":111222,
      "response":"error dialing remote address: dial tcp 200.142.130.219:25: i/o timeout",
      "sg_message_id":"JaMBs8eGS5C7muIyC7ClEQ.filter1097p1mdw1-16929-5890D26F-52.476",
      "sg_event_id":"RFa96TDwRY6Y3f6rq8C0bw",
      "marketing_campaign_name":"2\u00aa PalestraOnLine - Face",
      "event":"deferred",
      "tls":0,
      "email":"andrea.xxxx@xxxx.com.br",
      "attempt":"31",
      "smtp-id":"<JaMBs8eGS5C7muIyC7ClEQ@ismtpd0001p1iad1.sendgrid.net>",
      "timestamp":1486140013,
      "asm_group_id":2035,
      "marketing_campaign_id":873227,
      "category":[]
   }
]

[  
   {  
      "ip":"66.102.8.29",
      "sg_user_id":111222,
      "sg_event_id":"YWVlZWY2MzMtZTU0Ny00NTgzLTk4NzQtNDI1MTQwNWI2MDEx",
      "sg_message_id":"Xv_4DonCQpG47JydGDgoSA.filter0447p1mdw1-9064-5891EFEB-40.96",
      "useragent":"Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)",
      "event":"open",
      "marketing_campaign_name":"Amigo_Indica_Amigo",
      "email":"corretoraxxx@xxx.com",
      "asm_group_id":1821,
      "timestamp":1486143350,
      "marketing_campaign_id":873071,
      "category":[]
   }
]

[  
   {  
      "ip":"198.21.0.135",
      "status":"4.7.1",
      "sg_message_id":"JaMBs8eGS5C7muIyC7ClEQ.filter1097p1mdw1-16929-5890D26F-52.172",
      "marketing_campaign_name":"2\u00aa PalestraOnLine - Face",
      "email":"contato@xxxxx.com.br",
      "timestamp":1486147298,
      "smtp-id":"<JaMBs8eGS5C7muIyC7ClEQ@ismtpd0001p1iad1.sendgrid.net>",
      "marketing_campaign_id":873227,
      "category":[],
      "sg_user_id":111222,
      "sg_event_id":"F_SXgsl0QxOG1y4sWiQVqw",
      "reason":"454 4.7.1 <contato@xxxxx.com.br>: Relay access denied ",
      "event":"bounce",
      "tls":0,
      "asm_group_id":2035,
      "type":"blocked"
   }
]`

**Comment by Jericho** [comment]
ok I think I understand now: the `sg_user_id` is included in the JSON if the event (such as click, open, etc) if this event is associated with a marketing campaign but this value is not included in the JSON if the event is associated with a 'regular' email. This is very similar to `marketing_campaign_id` which maps to `public long? MarketingCampaignId { get; set; }` on the Event class.

Therefore, we can add a new property on the Event class like this:
```CSharp
public long? UserId { get; set; }
```

By the way, what does this value correspond to? Is it the unique identifier of the recipient?

**Comment by lsshenrique** [comment]
I am just approving a new project and verifing all information received from SendGrid, in order to know how to use them in the future, but at the moment I'm still not using the UserID value.
