### ISSUE TITLE
Mail.SendAsync should return the X-Message-Id

### ISSUE THREAD

**Issue by lsshenrique** [Jericho/StrongGrid#120]
When sending a request to the Send Mail API, it returns a response that contains the value "X-Message-Id", the value can be used to trace this email later through Webhooks.

A example:
`var response = await client.RequestAsync(method: SendGridClient.Method.POST, urlPath: "mail/send", requestBody: data);` 
` Console.WriteLine(response.StatusCode);` 
` Console.WriteLine(response.Body.ReadAsStringAsync().Result);` 
` Console.WriteLine(response.Headers.ToString());` 
` Console.ReadLine();`

**Comment by Jericho** [comment]
This is news to me. [SendGrid's documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html) simply states that the response will be HTTP 202. This is the sample response in their documentation:
```CSharp
{
  HTTP/1.1 202
}
```
I am searching their documentation and I don't see any reference to this "X-Message-Id". Can you point me to the reference?

**Comment by lsshenrique** [comment]
I didn't find this in the SendGrid's documentation, but in the examples of [SendGrid API](https://github.com/sendgrid/sendgrid-csharp/blob/master/examples/mail/mail.cs). The X-Message-Id comes in the response header of request. 

**Debug in my visual studio:**
![sendtest](https://cloud.githubusercontent.com/assets/25511742/23083754/6236269a-f546-11e6-992e-5b4113b52dfe.jpg)

**Activity SendGrid:**
![sendgridmessageid](https://cloud.githubusercontent.com/assets/25511742/23083757/6438d870-f546-11e6-8258-151e04305b7b.png)

I just got the solution for my case, I forced a cast on the object task. I think it would help if the task was typed with your result.

Headers:
```
-		headers	{Connection: keep-alive
X-Message-Id: atvn0ffCSk2MyTuUqygPag
X-Frame-Options: DENY
Access-Control-Allow-Origin: https://sendgrid.api-docs.io
Access-Control-Allow-Methods: POST
Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
Access-Control-Max-Age: 600
X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html
Date: Fri, 17 Feb 2017 20:59:21 GMT
Server: nginx
}	System.Net.Http.Headers.HttpResponseHeaders
```

**Solution with Cast**
```
            HttpResponseMessage resposta = ((dynamic)task).Result.Message;

            string messageId;

            if (resposta.Headers.Contains("X-Message-Id"));
                messageId = resposta.Headers.GetValues("X-Message-Id").FirstOrDefault();
```

**Comment by Jericho** [comment]
What if we changed the signature of the `SendAsync` method to return a string. Something like this:

```CSharp
public async Task<string> SendAsync(...)
```

The returned string would be the message Id.

**Comment by lsshenrique** [comment]
Yes, it's good. thank you!
