### ISSUE TITLE
How to make this ParseEmail work with IhttpActionResult instead of IActionResult

### ISSUE THREAD

**Issue by shyamal890** [Jericho/StrongGrid#145]
I am trying to use this library with `WebApi2` and it doesn't support `IActionResult` hence can't utilize `Request.Body` as mentioned in the example in `Read.me` file

**Comment by Jericho** [comment]
Surely there is a way for you to get the body of the request posted to your API? Maybe it's a little different that the example in the readme, but I'm sure you can figure it out.

The following example is from memory, so you may have to debug a little but I think it's probably pretty close to what you need:

```csharp
namespace WebApplication1.Controllers
{
    public class SendGridController : ApiController
        public IHttpActionResult ReceiveEvents()
        {
            var requestBody = await Request.Content.ReadAsStringAsync(); 
            var parser = new WebhookParser();
            var events = parser.ParseWebhookEvents(requestBody);

            ... do something with the events ...
        }
}
```

**Comment by shyamal890** [comment]
I tried `var requestBody = await Request.Content.ReadAsStreamAsync();` as stream is what `parser.ParseInboundEmailWebhook(--stream--);` accepts. However, I get an error when I try to do so.

**Comment by Jericho** [comment]
What do you mean by "an error"? Do you have any details? Stack trace? I'm afraid that without any details I will not be able to help further.

**Comment by shyamal890** [comment]
I found out why it was breaking. Here is the said issue in detail: https://github.com/Jericho/StrongGrid/issues/146
