### ISSUE TITLE
Bug: Parser breaks if `to` or `from` contains only email

### ISSUE THREAD

**Issue by shyamal890** [Jericho/StrongGrid#146]
If say the `to` property contains only `someone@email.com` then the parser breaks at 3rd line as there would be only one `substring` in the `piecesFrom` array as `MailAddress` refers to `piecesFrom[1]` which is not present. Moreover, there can be more than one email addresses in `to` property. 

```
           // Convert the 'from' from a string into a strongly typed object
            var rawFrom = parser.GetParameterValue("from", string.Empty);
            var piecesFrom = rawFrom.Split(new[] { '<', '>' }, StringSplitOptions.RemoveEmptyEntries);
            var from = new MailAddress(piecesFrom[1], piecesFrom[0].Replace("\"", string.Empty).Trim());
```

I handled this by tweaking the code as:

```
// Convert the 'to' from a string into a strongly typed object
            var rawTo = parser.GetParameterValue("to", string.Empty);
            var rawEmails = rawTo.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries).ToList();
            List<MailAddress> to = new List<MailAddress>();
            foreach(var re in rawEmails)
            {
                List<string> piecesTo = rawTo.Split(new[] { '<', '>' }, StringSplitOptions.RemoveEmptyEntries).ToList();
                if (piecesTo.Count() <= 1) { piecesTo.Add(""); }
                var to_email = new MailAddress(piecesTo[1], piecesTo[0].Replace("\"", string.Empty).Trim());
                to.Add(to_email);
            }
```

**Comment by Jericho** [comment]
Can you post an example of the JSON you received from SendGrid that illustrate the two scenarios you just mentioned:
- email address without a name
- multiple 'to'

**Comment by shyamal890** [comment]
This is how the to field looks like:

`p+123@something.com, Someone Surname <someone@gmail.com>`

**Comment by Jericho** [comment]
ok thanks. I'll fix the bug caused by "email address without a name" in this ticket and create a separate ticket to address multiple 'to' because it will be a breaking change (I will have to change the type of the 'To' property on the `Model.Webhook.InboundEmail` class from `MailAddress` to `MailAddress[]`.
