### ISSUE TITLE
Create Contact Fails

### ISSUE THREAD

**Issue by wcrowe** [Jericho/StrongGrid#147]
var contactId = await client.Contacts.CreateAsync(email, firstName, lastName);

Fails with error "request body is invalid";

It is passing the sendgrid api json {"email":"jdoe@gmail.com","first_name":"John","last_name":"Doe"}
where it needs to be [{"email":"jdoe@gmail.com","first_name":"John","last_name":"Doe"}]

**Comment by Jericho** [comment]
hummmm this is strange. There's an integration tests that creates, updates and deletes a contact and I don't see the error you are mentioning.

Here's the code in the integration test:

```csharp
var email = "111@example.com";
var firstName = "Robert";
var lastName = "Unknown";
var customFields = new Field[]
{
	new Field<string>("nickname", "Bob"),
	new Field<long?>("age", 42),
	new Field<DateTime>("customer_since", new DateTime(2000, 12, 1))
};
var contactId = client.Contacts.CreateAsync(email, firstName, lastName, customFields).Result;
Console.WriteLine($"Contact {contactId} created: {firstName} {lastName}");
```

**Comment by Jericho** [comment]
I did a little more investigation and turns out I was wrong and you are absolutely right: creating contacts throws an error. I'll get this fixed and include in release 0.24.0

**Comment by Jericho** [comment]
Also, I see the exact same problem when updating a contact. Fixing this issue as well...

**Comment by Jericho** [comment]
As best as I can tell this bug was introduced in 0.21.0 which was released on February 18 2017.

**Comment by wcrowe** [comment]
Thanks man.  I was in the process of writing what you have already done
until I found your library.  I don't want to reinvent the wheel and
sendgrid's package is a good example of what not to do

**Comment by Jericho** [comment]
Thanks for the compliments.

When I read the issue you created I didn't give you the benefit of the doubt. I knew I had tested this functionality a long time ago and couldn't believe it didn't work. I hope I didn't come across as dismissive (and I apologize if I did!), it was not my intention.

I will have 0.24.0 released in the next few hours.

**Comment by wcrowe** [comment]
That's great.  No real down time, I appreciate your hard work.
