### ISSUE TITLE
Parse plain text email

### ISSUE THREAD

**Issue by nheath99** [Jericho/StrongGrid#161]
Apologies for raising this as an issue, how would I get the email body if the parsed email is a plain-text message? The Html property of InboundEmail is empty if I receive a plain-text email, but populated with the email body if html. Thanks

**Comment by Jericho** [comment]
Can you please post an example of the JSON you received from SendGrid? To be honest I haven't seen an Inbound email webhook that didn't have HTML content.

**Comment by Jericho** [comment]
Currently, the inbound email parser looks for a parameter called `html` in data submitted by SendGrid in the webhook. In your case, I suspect this parameter is empty and there is another parameter called something like `text` (or something like that). I won't know for sure until I can see a sample.

**Comment by nheath99** [comment]
http://requestb.in/1g1yxza1?inspect

Yes you are right, there is a parameter called "text".

**Comment by nheath99** [comment]
http://requestb.in/1g1yxza1?inspect

FYI if sending an HTML email, the "text" property is also populated with the raw text of the email. Could this be exposed as a parsed property?

**Comment by Jericho** [comment]
Excellent! Thanks for the samples. 

Indeed I see `text` in addition to `html` which means that both of these values should be exposed as parsed properties.

What's surprising, is that SendGrid does not mention `text` in their [documentation about the inbound parse webhhook parameters](https://sendgrid.com/docs/Classroom/Basics/Inbound_Parse_Webhook/setting_up_the_inbound_parse_webhook.html#-Default-Parameters).
