### ISSUE TITLE
Mocking IClient resources

### ISSUE THREAD

**Issue by spib** [Jericho/StrongGrid#169]
Hi,

I want to mock out the IClient when unit testing my code, but because the resources (IClient.Mail for example) are concrete types that becomes difficult.

Should you perhaps introduce interfaces for the resources or is there another way to do this?

**Comment by Jericho** [comment]
I was hoping IClient would be enough for most unit testing scenarios and I wouldn't have to write an interface for each of the 28 resources. but I guess your experience demonstrates that I do need all those interfaces. I'll start working on it today.

**Comment by Jericho** [comment]
In the mean time, let me show how I mock http calls:

_Step 1:_
add a reference to this awesome nugetpackage: RichardSzalay.MockHttp

_Step2:_
write your unit test something like this:

```csharp
[Fact]
public void Send_response_with_message_id()
{
	// Arrange
	var mockHttp = new MockHttpMessageHandler();
	mockHttp.Expect(HttpMethod.Post, "https://api.sendgrid.com/v3/mail/send")).Respond((HttpRequestMessage request) =>
	{
		var response = new HttpResponseMessage(HttpStatusCode.OK);
		response.Headers.Add("X-Message-Id", "abc123");
		return response;
	});
	var mockHttpClient = httpMessageHandler.ToHttpClient();
	var client = new StrongGrid.Client(mockHttpClient);

	// Act
	var result = client.Mail.SendAsync(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, CancellationToken.None).Result;

	// Assert
	result.ShouldBe("abc123");
}
```

**Comment by spib** [comment]
Thanks, I was able to get around this using RichardSzalay.MockHttp so you can close this if you don't want to add those extra interfaces

**Comment by Jericho** [comment]
I will be publishing a new release with interfaces for all resources shortly.
