### ISSUE TITLE
issue with newtonsoft dependency

### ISSUE THREAD

**Issue by ukjeep4x4** [Jericho/StrongGrid#174]
we are getting an error with a dependency for newtonsoft 6.0.1, we have 9.0.1 installed(which is what is required b/c of the nuget pkg).  any help would be much appreciated.

![newtonsofterror](https://user-images.githubusercontent.com/29954486/27920604-269c4fdc-6243-11e7-889c-bdfc6c2b1567.png)

**Comment by Jericho** [comment]
StrongGrid does not reference Newtonsoft.Json version 6.0 and, as far as I know, neither do any of the referenced nuget packages so I'm really confused by this error message. Can you provide a way for me to reproduce this problem (maybe you could point me to a github repo with your ASP.NET project)?

In the mean time have you tried googling this issue? For example, I found the following which could be helpful:
- https://social.msdn.microsoft.com/Forums/azure/en-US/a75734f9-ccb4-417a-8c89-05f079107647/could-not-load-file-or-assemby-newtonsoftjson-version4500-bindingredirect-problem?forum=windowsazurewebsitespreview
- https://stackoverflow.com/questions/22507189/could-not-load-file-or-assembly-newtonsoft-json-version-4-5-0-0-culture-neutr

**Comment by ukjeep4x4** [comment]
well it specifically references lines in your code, which is why i thought it would be on your end.  i don't even have paths like that on my machine.  also, when in debug it works fine from my machine, but when i roll it up to production it doesn't work.  not sure if that helps you look for it.  we only have 9.0.1 in our project, no references to 6.0 anywhere.

![stronggrid](https://user-images.githubusercontent.com/29954486/27926252-b8ecc062-6255-11e7-9cff-a5e8ec046151.PNG)

**Comment by ukjeep4x4** [comment]
also i looked at your two links, we do not have a bindingredirect for newtonsoft in our web.config anywhere.

**Comment by ukjeep4x4** [comment]
here is the full text of that exception:

[FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]
   System.Net.Http.Formatting.BaseJsonMediaTypeFormatter..ctor() +0
   System.Net.Http.Formatting.JsonMediaTypeFormatter..ctor() +75
   System.Net.Http.Formatting.MediaTypeFormatterCollection..ctor() +53
   Pathoschild.Http.Client.FluentClient..ctor(Uri baseUri, HttpClient client) +203
   StrongGrid.Client..ctor(String apiKey, String username, String password, String baseUri, String apiVersion, HttpClient httpClient) in **C:\projects\stronggrid\Source\StrongGrid\Client.cs:341**
   StrongGrid.Client..ctor(String apiKey) in **C:\projects\stronggrid\Source\StrongGrid\Client.cs:272**

**Comment by Jericho** [comment]
What version of the .NET framework do you use? The screenshot you posted in your original question says `Microsoft .NET Framework Version 4.0.30319` which leads me to believe you are using `4.0`. Am I right?

If that's the case, StrongGrid has been designed for `4.5.2` and `NetStandard 1.6` so that could be an issue.

**Comment by ukjeep4x4** [comment]
we use 4.5.2, which gets hosted by 4.0 on the server....

**Comment by ukjeep4x4** [comment]
since it's fluentclient, could you have a reference to an older version of fluentclient?

**Comment by Jericho** [comment]
My interpretation of the error message (I could be wrong, without a way to reproduce I am simply guessing) is that version 6.0 of Newtonsoft.Json was found on the machine where the code is running which does not match the reference expected by FluentHttpClient. Maybe it's in your GAC or something?

**Comment by ukjeep4x4** [comment]
newtonsoft is not in the gac.  here is the dll file from the bin folder.  my interpretation of the error is that something is asking/requesting for that file and it can't find it on the server(bin folder) or in the gac.

![image](https://user-images.githubusercontent.com/29954486/27926946-26f9afd2-6258-11e7-8803-d8c683ec9748.png)

**Comment by ukjeep4x4** [comment]
so i'm looking at the dlls on my box in the packages, httpmultipartparser is version 2.2.0 on my box, but in production it's version 3.0.0

i'm thinking that is prob the issue.  it works correctly on my local box

**Comment by Jericho** [comment]
I didn't know they had release a version 3.0 to be honest. Let me review what changes they introduced since 2.2.0

**Comment by ukjeep4x4** [comment]
let me correct myself, httpmultipartparser is 2.2, pathoschild.http.fluentclient is 3.0, i misspoke

**Comment by Jericho** [comment]
ok, that makes more sense. FluentHtpClient 3.0 is indeed the desired version

**Comment by ukjeep4x4** [comment]
well i'm at a loss, can't figure out how to fix it or why it works in my debug mode, but not on the server.

**Comment by ukjeep4x4** [comment]
might have figured it out.  gimme a few minutes to make a web.config change.

**Comment by ukjeep4x4** [comment]
got it, i was missing this in my web.config:  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>

**Comment by Jericho** [comment]
Yes, binding redirection! That was mentioned in the articles I linked to earlier. 

I don't understand why you need this on your server though? oh well...
