### ISSUE TITLE
ParseInboundEmailWebhook() is not reading attachments

### ISSUE THREAD

**Issue by brendangreen** [Jericho/StrongGrid#176]
Hi,

I am sending an email that has an attachment included.

My (async) webapi controller is doing this:

    var parser = new WebhookParser();
    var inboundEmail = parser.ParseInboundEmailWebhook(await Request.Content.ReadAsStreamAsync());

Checking the attachments collection of `inboundEmail` via `inboundEmail.Attachments` and it's always empty.

Looking at the raw request body, we definitely see the attachments.  Snippet of the body is:

    --_004_SG2PR0101MB1133FD9BCA2C744E1C4F993AC3820SG2PR0101MB1133_
    Content-Type: image/png; name="2134.k.png"
    Content-Description: 2134.k.png
    Content-Disposition: attachment; filename="2134.k.png"; size=44610;
        creation-date="Wed, 16 Aug 2017 06:41:05 GMT";
        modification-date="Wed, 16 Aug 2017 06:41:05 GMT"
    Content-Transfer-Encoding: base64

    iVBORw0KGgoAAAANSUhEUgAAA20AAAJgCAIAAAHhfixhAAAAAXNSR0IArs4c
    ...rest of data to follow...

Is there something that we're missing?  The test emails are being sent from Outlook Web (Office 365) with an attachment dragged onto the message.
All other properties (that we care about) are being read without issue.

We are using version 0.28.0, added to our project via Nuget.

Cheers,
Brendan

**Comment by Jericho** [comment]
Hi, the `Attachment` property is indeed supposed to contain all the info about the attachements posted to your webhook by the SendGrid API. Can you show me a full example of the data posted to you by SendGrid to help me attempt to reproduce the issue?

**Comment by Jericho** [comment]
I just did a quick test: I sent an email with a screenshot pasted in the body of the email and also with a text file attached. The `InboundEmail` parser correctly parsed the two attachments so there must be something specific to the email you sent.

By the way, I am assuming you followed SendGrid's instructions to setup whitelabeling and also to setup the inbound email webhook, right?

**Comment by Jericho** [comment]
I keep looking at the snippet you posted this morning and I notice one thing that seems odd to me: `Content-Disposition: attachment; filename="2134.k.png";` 

I'm not 100% sure about this, but the reason why this looks odd to me is because SendGrid is using HTTP POST to send the content of the inbound email to your webhook URL and therefore the content-disposition should be `form-data`.

**Comment by brendangreen** [comment]
Jericho,

Really appreciate the comments and feedback - apologies for a late update (timezone differences, was in bed).

Turns out the webhook had the Send Raw flag checked, which is the root of the problem.

I've turned this off, and the Webhook parser is working brilliantly.

As an aside, I thought the SendGrid documentation on this flag kinda makes it sound like you MUST have it checked.

So everything is working perfectly.

Appreciate the library and your time.

Cheers,
Brendan

**Comment by Jericho** [comment]
Thanks for letting me know that turning on the 'POST the raw, full MIME message' option caused this issue. I went back to [SendGrid's documentation](https://sendgrid.com/docs/Classroom/Basics/Inbound_Parse_Webhook/setting_up_the_inbound_parse_webhook.html) and found the following warning which I had not paid attention to previously:

`If you do not check Send Raw, the post will be multipart/form-data with the email content URL encoded, but the attachments will be in multipart/form-data. If your code is only set up to read URL encoding, attachments could be dropped.`

The StrongGrid parser indeed expects attachments as `multipart/form-data` which explains why, in your case, the attachments were lost.

I completely agree with you that the wording of this warning leads you to believe that enabling this option is the preferred option.
