### ISSUE TITLE
Support 'on-behalf-of' header

### ISSUE THREAD

**Issue by Jericho** [Jericho/StrongGrid#177]
I just noticed something new in SendGrid's API: looks like we can add a [`on-behalf-of` header](https://sendgrid.api-docs.io/v3.0/how-to-use-the-sendgrid-v3-api/on-behalf-of) to most (but not all) API calls which allows operations to be executed on behalf of another subuser.

The documentation clearly says that the `on-behalf-of` header does not work with the mail.send API, but I also found a few resources, such as batches, campaigns, teammates, etc. (see below for complete list), where this header is not documented. Is that just an oversight in the documentation or does it mean they don't support this header?

UPDATE (11/8/17): The SendGrid [documentation](https://sendgrid.com/docs/API_Reference/api_v3.html) was updated and the oversights were corrected. Here's the full list of resources that accept the new header:

- [x] Access Management
- [x] Alerts
- [x] API keys
- [x] Blocks
- [x] Bounces
- [x] Categories
- [x] Contacts
- [x] Custom Fields
- [x] Global suppressions
- [x] Invalid emails
- [x] Lists
- [x] Segments
- [x] Sender Identities
- [x] Settings
- [x] SPAM reports
- [x] Stats
- [x] Suppressions
- [x] Templates
- [x] Unsubscribe groups
- [x] User profile
- [x] Webhooks Settings
- [x] Whitelabel domains
- [x] Whitelabel IPs
- [x] Whitelabel links

**Comment by Jericho** [comment]
After discussion with SendGrid folks, it received confirmation that the following ressources do not support impersonation:

- IP Addresses
- IP Pools
- IP Warmup
- Mail send
- Subusers
- Teammates

Al other resources support impersonation.

**Comment by pkkim** [comment]
Hello, I know that this is an old thread but I have just tested impersonation with IP pools within a subuser, and it does work. Specifically, a while ago I created a subuser and assigned IPs to it using the parent account API key. Just now, using impersonation, I created an IP pool, added an IP, deleted the IP from the pool, and deleted the pool, and everything worked.

**Comment by Jericho** [comment]
Thanks for sharing your experience. What you are saying is amazing. I was specifically told by a SendGrid product manager that IP management was not allowing impersonation.
