### ISSUE TITLE
Version of Pathoschild.Http.FluentClient out of sync between package reference and nuspec dependency

### ISSUE THREAD

**Issue by dasMulli** [Jericho/StrongGrid#199]
The version of `Pathoschild.Http.FluentClient` referenced by the csproj is out of sync with the dependencies listed in the `nuspec` file, causing a conflict in projects consuming this library.

Discovered it while diagnosing this StackOverflow question:
https://stackoverflow.com/questions/46569524/how-to-diagnose-warning-msb3277-found-conflicts-between-different-versions-of-t/46570092#46570092

**Comment by Jericho** [comment]
Thanks for reporting this issue. We shouldn't be using the .nuspec anymore since we upgraded our solution from .xproj to .csproj
