### ISSUE TITLE
Unix datetime conversion issue in Blocks.GetAllAsync

### ISSUE THREAD

**Issue by nitro52** [Jericho/StrongGrid#205]
I noticed when using Client.Blocks.GetAllAsync that there appears to be a datetime conversion issue. I'm trying to get blocks, persist them in a local db and later use the max created date time as the StartDate. But when i do this i'm seeing duplicates. 

I did some testing and this is what i found.

Direct Value from SendGrid API Response: 1510164515
.net Date while debugging:  {8/11/2017 6:08:35 PM}
Next request in .net startDate  = {8/11/2017 6:08:35 PM}
Raw value sent to Sendgrid (from fiddler trace) = 1510135715

I ran both the original value and next request through an online converter and this is what i found
Sendgrid Response
1510164515 through online converter = Wednesday, November 8, 2017 6:08:35 PM (Matches .net DateTime)

StrongGrid Request
1510135715 through online converter = Wednesday, November 8, 2017 10:08:35 AM (No longer matches original request)

Seems like the issue is when it goes to send the next request. any thoughts?

**Comment by Jericho** [comment]
The difference is exactly 4 hours? This sounds like a timezone issue.  Could it be that dates returned by SendGrid are in a given timezone but the date you send in the start date on your subsequent call is in a different timezone?

**Comment by nitro52** [comment]
i did some more digging and i can see you have some tests for the conversion extensions that Blocks.GetAllAsync uses. 

I added a from and to test and it looks like it passes

		[Fact]
		public void FromUnixTimeToUnixTime_UnixTime()
		{
			// Arrange
			var unixTime = 1510164515L;

			// Act
			var dateTime = unixTime.FromUnixTime();
			var result = dateTime.ToUnixTime();

			// Assert
			result.ShouldBe(unixTime);
		}

This does suggest the issue is elsewhere. i'll have to do some more digging.

**Comment by nitro52** [comment]
Ok found the problems, the issue is when i write it to SQL. If i cut out sql from the steps then the end result is the same as the original unix time stamp. What was confusing is that when i read the value from sql its the same, however i missed that the DateTime has a Kind property. this is set to UTC for the StrongGrid response and Unknown after its read from SQL.
