### ISSUE TITLE
HttpMultipartParser.MultipartParseException: Unexpected end of stream

### ISSUE THREAD

**Issue by satinjeet** [Jericho/StrongGrid#206]
hey Jericho,

on parsing an incoming email with attachments, I always see this exception 

`HttpMultipartParser.MultipartParseException: Unexpected end of stream`

here is the stack copied from a unit test:
```
Test Name:	Test_Raw_Email_Parsing_For_Attachments
Test FullName:	Test.UAC_Tests.UAC_Test_Raw_Email_Parsing.Test_Raw_Email_Parsing_For_Attachments
Test Source:	C:\...\Test\UAC_Tests\UAC_Test_Raw_Email_Parsing.cs : line 15
Test Outcome:	Failed
Test Duration:	0:00:10.9205948

Result StackTrace:	
at HttpMultipartParser.StreamingMultipartFormDataParser.ParseSection(RebufferableBinaryReader reader)
   at HttpMultipartParser.StreamingMultipartFormDataParser.Parse(RebufferableBinaryReader reader)
   at HttpMultipartParser.StreamingMultipartFormDataParser.Run()
   at HttpMultipartParser.MultipartFormDataParser..ctor(Stream stream, String boundary, Encoding encoding, Int32 binaryBufferSize)
   at StrongGrid.WebhookParser.ParseInboundEmailWebhook(Stream stream)
   at Test.UAC_Tests.UAC_Test_Raw_Email_Parsing.Test_Raw_Email_Parsing_For_Attachments() in C:\Test\UAC_Tests\UAC_Test_Raw_Email_Parsing.cs:line 19
Result Message:	
Test method Test.UAC_Tests.UAC_Test_Raw_Email_Parsing.Test_Raw_Email_Parsing_For_Attachments threw exception: 
HttpMultipartParser.MultipartParseException: Unexpected end of stream
```

here is the raw email I used for this test https://pastebin.com/dup1hCWk

**Comment by satinjeet** [comment]
@Jericho

**Comment by satinjeet** [comment]
Also I see the the dependency on Multipart Parser is set to 2.2.1, do you think updating to 2.2.4 might be helpful ?

**Comment by Jericho** [comment]
Can you share some code to help reproduce? Also, I see some weird characters in your email:
![image](https://user-images.githubusercontent.com/112710/32805896-d1ae4570-c958-11e7-97cc-d999b11da614.png)

Updating Multipart nuget package will not help. The package author released 3 versions last summer:
- version 2.2.2 adds support for .net 4.5 and 4.5.1 which are no longer supported by Microsoft so it doesn't really make sense to me. Besides, StrongGrid doesn't target .net 4.5 so this version is not helpful to us
- version 2.2.3 adds support for .net 4.6 which also doesn't make sense to me since the package already supported 4.5.2
- the author has signed his assembly in version 2.2.4 which is not helpful to investigate or resolve the situation you are reporting.

**Comment by Jericho** [comment]
Something else that looks weird to me: there are no line feeds between the sections of your sample raw email.

**Comment by Jericho** [comment]
To clarify my last comment, take a looks at a typical email as received from SendGrid webhook:
![image](https://user-images.githubusercontent.com/112710/32807571-49d1590c-c95e-11e7-9a41-8031b7624d5c.png)

and here's what your sample looks like:
![image](https://user-images.githubusercontent.com/112710/32807594-5e24bd36-c95e-11e7-9405-1be10ce02fef.png)

Notice how your sample is on a single line while a typical email has line feeds to separate sections.

**Comment by satinjeet** [comment]
this is a sample which was logged in to database by the application in case of failure. I will double check the source. Let me get you a new sample. soon.

**Comment by Jericho** [comment]
I used your sample email in my `WebhookParseTests.InboundEmail` unit test and I confirm that I am witnessing the same `Unexpected end of stream` exception.

More than likely this error is caused by the lack of proper line feeds.

**Comment by satinjeet** [comment]
@Jericho I tried switching email webhook to send data to my local server and started debugging it on VS and parsing works as expected. I could see all the attachments and other fields. Then switching it back seemed to remove the "End of stream" error. I have not seen that error happen since. I am assuming some bad data made its way to the webhook through some mistake. It is very confusing. but now everything seems to be working.

If I see an error again, I will give you the sample of the email causing problems.
