### ISSUE TITLE
Segment without list has listId 0

### ISSUE THREAD

**Issue by tmacht** [Jericho/StrongGrid#213]
When retrieving a segment that does not belong to a list (but is a segment of all contacts), the listId is 0, but the listId should be nullable and null in those cases.

**Comment by Jericho** [comment]
It didn't occur to me that `listId` was optional. I reviewed [documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Create-a-Segment-POST) and they indeed confirm that it's optional:

> Segments: Body contains a JSON object with conditions, a list of conditions as described below, a unique name, and an optional list_id, which is a valid list ID for a list to limit the search on. 

This means that I not only need to make it optional in the `Segment` model class (as you pointed out), but also when creating a new segment (the `listId` is currently required in the `Segments.CreateAsync` method).
