### ISSUE TITLE
Personalisation issue

### ISSUE THREAD

**Issue by NagashreeHS** [Jericho/StrongGrid#215]
Hi Team,

When I make async request using personalisation, I get automatic unsubscribe option in the email. 
I have set it to false.

```
var trackingSettings = new TrackingSettings
{
    ClickTracking = new ClickTrackingSettings
    {
        EnabledInHtmlContent = true,
        EnabledInTextContent = true
    },
    OpenTracking = new OpenTrackingSettings { Enabled = true },
    SubscriptionTracking = new SubscriptionTrackingSettings { Enabled = false }
};
```
It is also happening in other methods such as below

_Client.Mail.SendToSingleRecipientAsync(Model.ToAddress, Model.FromAddress, Model.Subject, Model.HtmlContent, Model.TextContent, EnableOpenTracking, EnableClickTracking);

Though subscriptionsettings is null,  I get unsubscribe link in email. Link is not visible in mailinator box/outlook. 

It is only visible in other web email box.

Please advise.

**Comment by Jericho** [comment]
I am not able to reproduce the issue you are describing. I can send emails to myself without the unsubscribe link such as this example:
![image](https://user-images.githubusercontent.com/112710/37144082-028d8c9c-228b-11e8-8c4d-14ddff384832.png)

Can you provide a more complete C# sample and/or steps to reproduce the issue?

**Comment by NagashreeHS** [comment]
Hi,

I copied example from your test method

  public async Task<bool> TestPersonalisationAsync(string subject)
        {
            try
            {
               
                var from = new MailAddress(_appEnvironment.EmailFrom, _appEnvironment.EmailFromDisplayName);
                var to1 = new MailAddress("nagashree.shivashankar@dbt.co.uk", "Recipient1");
                var to2 = new MailAddress("recipient2@mailinator.com", "Recipient2");
                var textContent = new MailContent("text/plain", "Hello world!");
                var htmlContent = new MailContent("text/html", "<html><body>Hello <b><i>{{first_name}}!</i></b><br/></body></html>");
                var htmlContent = new MailContent("text/html", htmlTemplate);
                var personalizations = new[]
                {
                    new MailPersonalization
                    {
                        To = new[] { to1 },
                        Substitutions = new KeyValuePair<string, string>[]
                        {
                            new  KeyValuePair<string, string>("-name-", "Nagashree")
                        },
                        CustomArguments = new KeyValuePair<string, string>[]
                        {
                            new  KeyValuePair<string, string>("AccountRef", "ABC_123")
                        }

                    }
                    
                };
              
                var trackingSettings = new TrackingSettings
                {
                    ClickTracking = new ClickTrackingSettings
                    {
                        EnabledInHtmlContent = true,
                        EnabledInTextContent = true
                    },
                    OpenTracking = new OpenTrackingSettings { Enabled = true },
                    SubscriptionTracking = new SubscriptionTrackingSettings { Enabled = false }
                };
               
                var customArgs = new KeyValuePair<string, string>[]
                {
                new  KeyValuePair<string, string>("sent_on", DateTime.UtcNow.ToString("yyyy-MM-dd HH-mm-ss")),
                new  KeyValuePair<string, string>("BatchId", "1234")
                };
                
                var messageId = await _Client.Mail.SendAsync(personalizations, subject, new[] { textContent, htmlContent }, from,
                    customArgs: customArgs,
                    trackingSettings: trackingSettings
                   
                );
                return true;
            }
            catch(Exception ex)
            {
                return false;
            }

This issue cannot be reproduced with mailinator.com emails, I was able to reproduce it in our official email .

Attached screenshot
![unsubscribe](https://user-images.githubusercontent.com/20299831/37144449-fbc825d6-22b5-11e8-80db-2131ecdfbc0d.PNG)

**Comment by Jericho** [comment]
It sounds like your corporate email server is adding this link, not SendGrid.

**Comment by NagashreeHS** [comment]
Oh ok . Thanks for confirmation.

**Comment by Jericho** [comment]
Just curious: what happens when you click the link?

**Comment by NagashreeHS** [comment]
I get this message

![image](https://user-images.githubusercontent.com/20299831/37144845-296fa1fc-22b7-11e8-8fe6-f4db7b811dcb.png)

**Comment by Jericho** [comment]
This actually looks like an Outlook feature to me. don't you think?

**Comment by Jericho** [comment]
Here's a [discussion](https://stackoverflow.com/questions/41266990/how-to-make-the-unsubscribe-link-in-outlook-work-for-newsletters) about this topic which confirms this link is added by Outlook.

**Comment by NagashreeHS** [comment]
Yes thanks. I didn't realise that. Thanks for quick response. Very much appreciated.

Thanks,
Nagashree
