### ISSUE TITLE
Blocks.GetAsync() throws a json exception

### ISSUE THREAD

**Issue by cwensley** [Jericho/StrongGrid#216]
Currently the strong api returns a single Block object, but the SendGrid API v3 returns an array so Newtonsoft.Json throws an exception that the json isn't an object.

**Comment by Jericho** [comment]
I guess I was fooled by Sendgrid’s documentation which states that the purpose of this method is to “Get a specific block”!

But you’re right: a single email address can be blocked multiple times therefore it makes sense to return an array of block objects.

I’m away for a long weekend so I’ll take care of this early next week when I’m back. Hope that’s ok.

**Comment by cwensley** [comment]
@Jericho no problem at all!  I just found this project today and already migrated a few things over which has been a huge improvement in maintainability.  I actually found this bug during testing but am not using it in production (I'm using `GetAllAsync`), so there's no rush on a fix.

Thanks for the quick response!

**Comment by Jericho** [comment]
This is resolved in 0.37.0 which will be on nuget.org within the next hour.

**Comment by cwensley** [comment]
Beautiful, thanks for the quick fix!
