### ISSUE TITLE
Add ability to remove recipients from list in batch

### ISSUE THREAD

**Issue by hostr** [Jericho/StrongGrid#225]
This endpoint isn't documented in SendGrid's official documentation, but it does work. I'm hoping this can be added to StrongGrid even though it's unofficial.

Example HTTP Request would be:
`DELETE /contactdb/lists/{listId}/recipients`
```
[
	"abc123",
	"def456"
]
```

Body of the request includes SendGrid recipient ID's. This call is very similar to the Add Multiple Recipients to a List outlined here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Add-Multiple-Recipients-to-a-List-POST

**Comment by Jericho** [comment]
Thanks for PR #224.

I'm curious though: how did you discover this undocumented endpoint?

**Comment by hostr** [comment]
> how did you discover this undocumented endpoint?

Guess and hope. My project involves syncing contact lists between another source and SendGrid. Instead of running _possibly_ thousands of requests to remove recipients from lists, this request would be super helpful.

**Comment by Jericho** [comment]
I'm reviewing (and testing!) now. Assuming everything works as expected, I'll merge and release later today. I'll also open an issue on SendGrid's c# client repo to ask if the lack of documentation for this method was an oversight or if it was intentional.

**Comment by Jericho** [comment]
Resolved by 3b60689a6c0007b00d363550eb555233c44e7dfa
