### ISSUE TITLE
Parse Webhook; How to get an excel file from attachments?

### ISSUE THREAD

**Issue by Arganth** [Jericho/StrongGrid#235]
Hello, 

I need to parse incoming mails with excel attachments.
I take the incoming InboundEmail and write it to some storage media.
Read it back in and want to transform the attachment into a excel file.

The parsing/storing/reading works but the attachments are corrupt when i wan to open them.

Is there a package/some way to transform the attachment data to an excel file?

What it comes down to is this:

```csharp
if (inboundEmail.Attachments != null)
{
    foreach (InboundEmailAttachment a in inboundEmail.Attachments)
    {
        byte[] content = new byte[a.Data.Length];

        attachmentdata += a.ContentId + "\n";
        attachmentdata += a.ContentType + "\n";
        attachmentdata += a.FileName + "\n";
        attachmentdata += a.Id + "\n";
        attachmentdata += a.Name + "\n";

        await a.Data.ReadAsync(content,0, a.Data.Length);
        System.IO.File.WriteAllBytes(a.Name, content);
    }
}
```

**Comment by Jericho** [comment]
I am not observing any problems with attachments. I ran several tests and I can successfully receive Excel files and other types of attachments and I don't experience any "corruption".

In fact, here's a test you can try:

Extract the content of [InboundEmail.zip](https://github.com/Jericho/StrongGrid/files/2185777/InboundEmail.zip) to `C:\Temp` and run the code below:

```csharp
var body = new MemoryStream();
using (var file = new FileStream("C:\\Temp\\InboundEmail.bin", FileMode.Open, FileAccess.Read))
{
    byte[] bytes = new byte[file.Length];
    file.Read(bytes, 0, (int)file.Length);
    body.Write(bytes, 0, (int)file.Length);
}
body.Position = 0;

var parser = new WebhookParser();
var inboundEmail = parser.ParseInboundEmailWebhook(body);

if (inboundEmail.Attachments != null)
{
    foreach (var attachment in inboundEmail.Attachments)
    {
        byte[] content = new byte[attachment.Data.Length];
        attachment.Data.Read(content, 0, (int)attachment.Data.Length);

        System.IO.File.WriteAllBytes($"C:\\Temp\\{attachment.Name}", content);
    }
}
```

Reading from the `.bin` file simulates receiving a WebHook from SendGrid. After you run the code, you should see a new Excel file in your `C:\Temp` folder and you should be able to open it without any problem.

**Comment by Arganth** [comment]
AMAZING :)

Thank you very much for your help :)

As far as I know my error was (still have to fully investigate it) that I took the incoming post and saved it to Azure Blobstorage (as a txt file to see the contents). Then read it back in and wanted to transform the file back into an excel file. But then the file size in bytes does not match up anymore.

With your way i can do it differently now :)
