### ISSUE TITLE
IP Pools - Unexpected token

### ISSUE THREAD

**Issue by rlightner** [Jericho/StrongGrid#239]
```
Error reading string. Unexpected token: StartObject. Path 'ips[0]', line 1, position 9.
```
Looks like the object changed.
```json
{
  "ips": [
    {
      "ip": "xxx.xxx.xxx.xxx",
      "start_date": null,
      "warmup": false
    }
  ],
  "pool_name": "awesome_pool_name"
}
```

**Comment by Jericho** [comment]
What call did you make that caused this error? Also can you share a code sample to help me reproduce?

**Comment by Jericho** [comment]
Guess on my part: you are probably invoking `IpPools.Get(name, cancellationToken)`. The documentation says that `ips` should contain an array of string:

![image](https://user-images.githubusercontent.com/112710/44059538-b71d1838-9f1f-11e8-95ce-07407365e710.png)

They even provide the following sample:
```
HTTP/1.1 200 OK 

{
  "ips":["167.89.21.3"],
  "pool_name":"new_test5"
}
```

But clearly the sample you posted indicates that their own documentation is not in synch with their API.

**Comment by Jericho** [comment]
Ok I was able to reproduce: I created an IP pool and added an address to this pool. When I subsequently attempted to retrieve this pool I received the following JSON:

```
{"ips":[{"ip":"xxx.xxx.xx.xxx","start_date":null,"warmup":false}],"pool_name":"StrongGrid Integration Testing: updated name"}
```

which does not match SendGrid's own documentation and caused StrongGrid to throw a `Unexpected token` exception.

**Comment by rlightner** [comment]
Yup, sorry for the delay in responding.  They seem to be updating the API and not releasing a change log. Just like with the dynamic templates.

**Comment by Jericho** [comment]
Indeed. I'll post a question in their repo to ask if there are any other undocumented recent changes. 

In the mean time, give me a day or two and I'll publish a hot fix to handle this situation.

**Comment by Jericho** [comment]
@rlightner I'm being told that the issue you discovered is just an anomaly and they will fix their documentation. Also, they are saying that changes are logged [here](https://sendgrid.com/docs/release_notes.html).

**Comment by rlightner** [comment]
The issue I discovered is an anomaly? Wonder what that actually means.

**Comment by Jericho** [comment]
0.47.1 published to nuget.
