### ISSUE TITLE
Missing SmtpId field from GroupResubscribeEvent, UnsubscribeEvent, SpamReportEvent, GroupUnsubscribeEvent

### ISSUE THREAD

**Issue by KoditkarVedant** [Jericho/StrongGrid#247]
@Jericho According to the SendGrid document regarding the Event Webhook handler except `OpenEvent` and `CloseEvent` rest has the `smtp-id` present.

I was working on a implementation for SendGrid, I thought I could use the StrongGrid (As most of the code will be similar) but there are some differences in implementations. I also see we can remove some code from the library too as we have build in helpers.

**Comment by KoditkarVedant** [comment]
@Jericho I'm writing the Event Webhook parser which is quite similar what you have but I can not use your library directly until we have this changes release until then I'll use my version of parser.

**Comment by Jericho** [comment]
I just found this helpful chart (I don't remember seeing it before, must be new) which indicates that `smtp-id` is valid for all event types. We should review the information in this chart to ensure that all attributes are available in all events.

**Comment by KoditkarVedant** [comment]
@Jericho Hey I was referring to this [chart](https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html#-Event-objects) as I can see they have not `X` next to `open` and `close` events.

**Comment by Jericho** [comment]
A year and a half after we reported these inconsistencies, the documentation has finally been updated ([here](https://github.com/sendgrid/docs/pull/5868) and [here](https://github.com/sendgrid/docs/pull/5870))!

I will review the recently updated `Event Object` chart and make the appropriate adjustments in StrongGrid.

**Comment by Jericho** [comment]
Publishing an update shortly with several changes to webhook model C# classes to match the newly updated documentation. Let's hope their updated documentation is accurate!!!

**Comment by Jericho** [comment]
Just as I was getting ready to release the next version, I realized a few fields have been omitted from the documentation and I [reported this omissions](https://github.com/sendgrid/docs/issues/5889). I don't want to wait another year and a half to release this update so I will do my best to guess where the undocumented fields apply and I will go ahead with releasing StrongGrid.

**Comment by Jericho** [comment]
The confusion continues: https://github.com/sendgrid/docs/issues/5890
