### ISSUE TITLE
TLS is applicable for all events

### ISSUE THREAD

**Issue by KoditkarVedant** [Jericho/StrongGrid#248]
According to docs TLS can be returned for all events not just Delivery Events. At least they did not specify it is only related to Delivery Events.

**Comment by Jericho** [comment]
What's strange is that the [chart](https://sendgrid.com/docs/for-developers/tracking-events/event/#event-objects) does not have any 'X' in any of the column for the `tls` property. Is that a mistake in the documentation? I'll open an issue in the SendGrid repo to get clarification.

**Comment by Jericho** [comment]
I asked for clarification: https://github.com/sendgrid/sendgrid-csharp/issues/792

**Comment by Jericho** [comment]
A year and a half after we reported these inconsistencies, the documentation has finally been updated (here and here)!

Publishing an update shortly with several changes to webhook model C# classes to match the newly updated documentation. Let's hope that their updated documentation is accurate!!!
