### ISSUE TITLE
Using ParseInboundEmailWebhook in .NET Core

### ISSUE THREAD

**Issue by rgmills** [Jericho/StrongGrid#250]
Hi :wave:

First of all, thanks for the library it just saved me a ton of time :)

I did run into a few issues using in ASP.NET Core 2.1 and wasn't sure if it was something weird I was doing or it's expected and just not yet documented.  I started with the instructions at https://github.com/Jericho/StrongGrid#parser however ran into a couple issues:

1. Argument null exception thrown from `HttpMultipartParser`
   - Form Model Binding kicks in by default for `Content-Type: multipart/form-data` which causes an `Argument null` exception to be thrown by `HttpMultipartParser`.  After a bit of debugging, since model binding has processed/read the form and the underlying stream is non-seekable attempts to parse the stream yield an exception.
   - Fix: Add implementation for `DisableFormValueModelBindingAttribute` from https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.1 and add to your webhook controller action
2. Some encodings (such as Windows-1252) aren't supported by default in .NET Core.
    - I've noticed emails sent from Outlook.com use this encoding which isn't registered by default in .NET Core 
    - Fix: Add `System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);`

I can only confirm the above works for ASP.NET Core 2.1 (documentation seems to indicate it should work for older versions).  I'm not sure if either of the fixes make sense to bake into the library vs. adding to documentation.  I'd be glad to help either way.

**Comment by rgmills** [comment]
> Regarding issue 1: funny that you should mention a problem caused by a non-seekable stream causing an exception in the http multipart parser because I faced a very similar situation recently. In fact, I implemented a workaround and released it in version 0.48.0 So my first thought is that maybe you are not using the latest nuget package? Otherwise, it probably means that the workaround I implemented does not work in all scenarios. I'll wait for you to confirm that you are indeed using the latest package and if so, I'll have to invest time to attempt to reproduce your exact scenario. Speaking of which, any additional info, samples, etc. that will help me reproduce would be much appreciated.

The non-seekable stream would be a problem, but the ultimate culprit here was model binding was processing the stream before I had a chance to pass it off to the parser.  When I added a definition for `DisableFormValueModelBindingAttribute` and added it to the controller action everything worked fine.  So, `0.48.0` seems to be working just fine :)

> Regarding issue 2: this is news to me. I wasn't aware that some encodings where no "available" by default. I need to educate myself on whether a library can enable these encodings. But... one thing is bothering me: I use my personal Outlook on my desktop to send emails from my personal Hotmail address whenever I'm testing the parser and all webhooks are posted to my testing netcore2.1 (which, unless I'm mistaken, sounds exactly like your scenario) and I have never faced similar problem. There must be someything slightly different in your setup compare to mine.

When sending from the desktop, the encodings are available (us-ascii and/or utf-8). But, when testing from the web (outlook.com, or specifically in my case outlook.office.com since it's an O365 account), the content uses Windows-1252 encoding.  I have no idea why they encode differently, but 🤷‍♂️

**Comment by Jericho** [comment]
> but the ultimate culprit here was model binding was processing the stream before I had a chance to pass it off to the parser.

Turning off model binding makes this problem go away because the position pointer in the request stream is positioned at the beginning which allows http multipart parser to properly parse the request. But, in my opinion, the underlying problem persists: StrongGrid doesn't seem to be able to handle scenarios where the stream is non-seekable **AND** the position pointer is not at the beginning of the stream. The [workaround I recently implemented ](https://github.com/Jericho/StrongGrid/commit/dbaab9ae577d9d53ba7427877d89193b945700b9#diff-1e8f352a99bdc3078893493053e09348R62) was supposed to handle this scenario but maybe the underlying issue has nothing to do with the stream being seekable or not and/or nothing to do with the position of the pointer??? Maybe model binding somehow modifies the stream or something.

>  when testing from the web (outlook.com, or specifically in my case outlook.office.com since it's an O365 account), the content uses Windows-1252 encoding.

It never occurred to me to test from Hotmail's web interface.

**Comment by Jericho** [comment]
Just tested with a simple "hello world" email sent from Hotmail's web interface and the "charsets" in the payload received from SendGrid looks like this:
```
{{
  "to": "UTF-8",
  "html": "iso-8859-1",
  "subject": "UTF-8",
  "from": "UTF-8",
  "text": "iso-8859-1"
}}
```

I imagine that in your case the charset for `html` is different? Maybe there's some specific content in the body of your email that caused hotmail to switch to a different charset?

**Comment by rgmills** [comment]
The charset ends up being Windows-1252. Content wise, it's something like this.


" ' " ' " ' "

! @ # $ % ^ & * ( ) - + = [ ] { } : ; ‘ ‘ “ “ ” ` ~

________________________________

**Comment by Jericho** [comment]
It took me a while but I am finally able to reproduce `'Windows-1252' is not a supported encoding name.` by using the content you shared.

I am now investigating what (if anything) I can do to resolve. Stay tuned...

**Comment by Jericho** [comment]
After 2 days of investigation, I reached the same conclusion that you mentioned originally (you are way ahead of me!): to resolve this issue, StrongGrid needs to take a dependency on `System.Text.Encoding.CodePages` nuget package and register the missing encodings by adding the following line: `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);`.

**Comment by Jericho** [comment]
I created a separate issue for encodings so we can use this one to continue discussing the other issue you brought up (related to model binding) if you feel we should investigate further.

**Comment by Jericho** [comment]
Can you test the release candidate which is available in [my MyGet feed](https://www.myget.org/F/jericho/api/v3/index.json)? I tested that it solves the missing encodings issue, but I would appreciate outside confirmation.

**Comment by rgmills** [comment]
@Jericho - Hey, sorry was away for a bit.  Yep, I'll take a look shortly.  Looking at the change (https://github.com/Jericho/StrongGrid/commit/9a844f307e40644d0cc7cc0d9a6fe44652aed86f), it's more or less exactly what I did in code.

**Comment by rgmills** [comment]
Took a bit longer than planned, but looks good!

**Comment by Jericho** [comment]
Perfect. I’m away from my computer at the moment but I will publish to NuGet later today
