### ISSUE TITLE
How to use Campaigns class for sending campaign

### ISSUE THREAD

**Issue by swnasir** [Jericho/StrongGrid#251]
Hi, I am trying to use Campaigns class to create and send a campaign to the recipients. But I found an exception which states that Campaigns constructor is internal and is not accessible. 
Can anyone please let me know how to resolve the problem.

```
public async Task SendCampaign()
		{
			var apiKey = Environment.GetEnvironmentVariable("MY_SENDGRID_API_KEY");			
                        var httpClient = new System.Net.Http.HttpClient();
			var client = new FluentClient("https://api.sendgrid.com/v3/campaigns", httpClient);
			var campaigns = new Campaigns(GetFluentClient());
		}
```
Please let me know how can I use this.

**Comment by Jericho** [comment]
You should look at the [usage section](https://github.com/Jericho/StrongGrid#usage) in ReadMe for examples.

**Comment by swnasir** [comment]
> You should look at the [usage section](https://github.com/Jericho/StrongGrid#usage) in ReadMe for examples.


> You should look at the [usage section](https://github.com/Jericho/StrongGrid#usage) in ReadMe for examples.

al

**Comment by swnasir** [comment]
> You should look at the [usage section](https://github.com/Jericho/StrongGrid#usage) in ReadMe for examples.

Looked at the Readme file but did not found my answer. Can you please give me suggestions on creating Campaigns class to create a new campaign and send it by calling send grid web API.
