### ISSUE TITLE
CreateInboundParseWebhookSettings uses Patch instead of Post

### ISSUE THREAD

**Issue by SaltyDH** [Jericho/StrongGrid#253]
This results in a 404 error when the web request is made.

**Comment by Jericho** [comment]
You're right: [documentation](https://sendgrid.api-docs.io/v3.0/settings-inbound-parse/create-a-parse-setting) states that you must issue a POST to create a new inbound parse setting.

I'll fix this bug and publish a hotfix

**Comment by SaltyDH** [comment]
Awesome, thanks for that!
