### ISSUE TITLE
HttpMultipartParser version required 2.2.1

### ISSUE THREAD

**Issue by niksworld22** [Jericho/StrongGrid#255]
Could not load file or assembly 'HttpMultipartParser, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

above error throwing in following code:
i am using StrongGrid version 0.49.0.0

 public HttpResponseMessage SendTestQTX()
        {
            try
            {
                var parser = new WebhookParser();
             
                Stream inputStream = GetStream(INBOUND_EMAIL_WEBHOOK);
                var inboundEmail = parser.ParseInboundEmailWebhook(inputStream); // this line gives error

                //check if message exists
                if (inboundEmail != null)
                {
                    //assign values to be saved in DB
                    var qtxParsedData = new object();

                    List<FileUpload> fileUploadList = new List<FileUpload>();
                    // To access all Attachments
                    var attachments = inboundEmail.Attachments;

                    //create the list of email user's(To and Cc)to be saved
                    var toList = inboundEmail.To.Select(to => to.Email).ToList();
                    var ccList = inboundEmail.Cc.Select(cc => cc.Email).ToList();
                    List<EmailUser> emailUserList = new List<EmailUser>();
                    //get the list To users
                    foreach(var toEmail in toList)
                    {
                        EmailUser emailUser = new EmailUser()
                        {
                            UserEmail = toEmail,
                            UserType = EmailUserType.To,
                            EmailStatus = QTXEmailStatus.TempSaved
                            
                        };
                        emailUserList.Add(emailUser);
                    }
                    //get the list of Cc users
                    foreach (var ccEmail in ccList)
                    {
                        EmailUser emailUser = new EmailUser()
                        {
                            UserEmail = ccEmail,
                            UserType = EmailUserType.Cc,
                            EmailStatus = QTXEmailStatus.TempSaved
                        };
                        emailUserList.Add(emailUser);
                    }

                    //get the data from the inbound email as the QtxEmail object to save it temporarily
                    QTXEmail qtxEmail = new QTXEmail
                    {   
                        EmailUsers = emailUserList,
                        CreatedDate = DateTime.UtcNow,
                        SenderEmail = inboundEmail.From.Email,
                        SenderName = inboundEmail.From.Name,
                        EmailSubject = inboundEmail.Subject,
                        EmailBody = inboundEmail.Text,
                        EmailStream = ConvertStreamToByteArray(inputStream)
                    };

                    //save the Qtx email Entity
                    int qtxId = QTXEmailService.CreateQTXEmail(qtxEmail);
                    if (qtxId > 0)
                    {
                        return new HttpResponseMessage(HttpStatusCode.OK);
                    }
                    else
                    {
                        return new HttpResponseMessage(HttpStatusCode.InternalServerError);
                    }
                }
                else
                {
                    return new HttpResponseMessage(HttpStatusCode.BadRequest);
                }
            }
            catch (Exception ex)
            {
                string logId = Logger.LogException(ex, "Error in sendqtx. DateTime:" + DateTime.Now);
                return new HttpResponseMessage(HttpStatusCode.InternalServerError);

            }
        }

**Comment by niksworld22** [comment]
hi, 
can you check that what could be the issue on the line 
var inboundEmail = parser.ParseInboundEmailWebhook(inputStream); // this line gives error

and it requires me to install HttpMultipartParser version 2.2.1 but i was having 2.2.4

**Comment by niksworld22** [comment]
Hi, any solution for above?

**Comment by Jericho** [comment]
Is there a reason why your project is referencing HttpMultipartParser? Is that intentional? If not, I recommend you simply remove the reference from your project. If so, you’ll probably have to configure binding redirection. If you don’t want to setup redirection, you could consider downgrading your reference to 2.2.1. As far as I remember the author of that package did not introduce any new functionality between 2.2.1 and 2.2.4, he simply added support for an obsolete .net framework (framework 4.0 if I remember correctly), therefore there’s no incentive for you to reference 2.2.4 (unless you are using th obsolete framework of course).

**Comment by niksworld22** [comment]
Hi,
i have not added reference for HttpMultiPartParser additionally. Strong
Grid has the dependecy on HttpMultipartParser. so it is added by StrongGrid
automatically.

**Comment by Jericho** [comment]
Yes indeed StrongGrid references HttpMultiPartParser but my understanding of the error you are describing is that there is a second reference to this same NuGet package in your environment and to make matters worse, this second reference targets a different version of this package. 

Without more details and/or steps to reproduce this problem, it’s very difficult for me to provide better advice.
