### ISSUE TITLE
Inbound Parse Message-ID and In-Reply-To

### ISSUE THREAD

**Issue by daniebruwer** [Jericho/StrongGrid#257]
Trying to find this, but my headers seems to be empty.  Would it not make sense to add two properties on **InboundEmail** for **Message-ID** and **In-Reply-To**
Message-ID: <CAF1uySmzfR74gS7nUJB-rDs5XPw-=UE6=iOQMJP_H334RbmkFA@mail.gmail.com> In-Reply-To: <CAF1uySnzqqbLGD2WMnBEGdgXeuTzA7NEGZP=J4rCPt93oDFW-w@mail.gmail.com>

**Comment by Jericho** [comment]
The properties on the InboundEmail class are based on what SendGrid has [documented](). Look at the ‘Default parameters’ section, you’ll see that Message-Id and In-Reply-To are not documented as being included in the data sent from SendGrid. 

I’m going to guess that these two properties are probably included in the headers, but if I understand what you are saying the headers properties in your case is empty, is that right? If so, we need to understand why it’s empty. Any chance you can give me steps to reproduce or even better: show me the Json data you received from SendGrid.

**Comment by Jericho** [comment]
One more thing I just thought about: when you configured the webhook in the SendGrid UI, did you enable the « Send Raw » option? If so, disable it. I know that the format of the data posted by SendGrid is very different when you enable this option which could potentially explain why the headers property is empty.

**Comment by daniebruwer** [comment]
@Jericho thanks so much, the disabling raw option did the trick. It's available in the headers.
