### ISSUE TITLE
Which .Net framework should StrongGrid support?

### ISSUE THREAD

**Issue by Jericho** [Jericho/StrongGrid#273]
StrongGrids currently targets `net452`, `netstandard1.3` and `netstandard2.0`. I [conducted a survey](https://github.com/Jericho/StrongGrid/issues/219) about a year ago to determine if we needed to make a change to the list of targeted frameworks and the consensus was that we shouldn't make any changes. I think it's time to review if that's still the case. 

Some factors that lead me to think that we should review which frameworks we support:

- Microsoft [announced](https://devblogs.microsoft.com/dotnet/net-core-1-0-and-1-1-will-reach-end-of-life-on-june-27-2019/
) end-of-life for .net Core 1.0 and 1.1 which, presumable, will reduce the need for libraries targeting `netstandard1.x`. 
- The latest guidelines from Microsoft to library authors is to [avoid targeting netstandard1.x](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting). 
- Some of Microsoft's own nuget packages have stoped supporting `net452` in favor of `net461`. Case in point: Package System.Text.Encoding.CodePages supports `net461` but it does not support `net452`. This means that it will become more an more difficult to upgrade the packages we depend on.

All this to say that I would personnaly be inclined to support `net461` instead of `net452` and to drop support for `netstandard1.x` from StrongGrid. Before making any decision, I want to give everyone a chance to voice their opinion on this breaking change.

**Comment by dantheman999301** [comment]
I think those are acceptable.

**Comment by JWilliams-CINC** [comment]
I don't see any problems with that.

**Comment by Jericho** [comment]
This will be in release 0.56.0 (see #276).
