### ISSUE TITLE
Include status code when request fails

### ISSUE THREAD

**Issue by Jericho** [Jericho/StrongGrid#275]
When a request fails, StrongGrid throws an exception which only includes the error message returned from SendGrid. It would be useful to also include the HttpStatusCode.

This was suggested by @dantheman999301

**Comment by dantheman999301** [comment]
That looks good to me, can use that as a base and extend the PR tomorrow.

**Comment by Jericho** [comment]
If I don't get interrupted, I'll have 0.54.0 published later this afternoon with this enhancement
