### ISSUE TITLE
Subusers

### ISSUE THREAD

**Issue by Jericho** [Jericho/StrongGrid#28]

**Comment by Jericho** [comment]
Unfortunately, I do not access to this feature.

**Comment by beriniwlew** [comment]
I might be able to help with that.

**Comment by Jericho** [comment]
That would be great

**Comment by beriniwlew** [comment]
How do I get ahold of you outside of github?

**Comment by Jericho** [comment]
[gitter](https://gitter.im/StrongGrid/Lobby) is easiest.
