### ISSUE TITLE
UpdateVersionAsync fails with "cannot switch editors" message

### ISSUE THREAD

**Issue by jlcj1974** [Jericho/StrongGrid#288]
Looks like including the editor property when issuing an HTTP PATCH to /v3/templates/ for a specific template version in UpdateVersionAsync causes SendGrid to reject the PATCH with the error "You cannot switch editors once a transactional template version has been created."

In Fiddler, when I removed the "editor" property altogether from the payload, it accepted and updated the version correctly.

**Comment by Jericho** [comment]
Intriguing... 

SendGrid's [documentation](https://sendgrid.api-docs.io/v3.0/transactional-templates-versions/edit-a-transactional-template-version) indicates that you can edit the editor property of a template version but you seem to had found that it's not the case.

I will attempt to reproduce tomorrow.

**Comment by jlcj1974** [comment]
Interesting. I was looking at this API [documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/versions.html) which doesn't include it.

**Comment by Jericho** [comment]
This wouldn't be the first time we discover discrepancies in SendGrid's documentation!

**Comment by Jericho** [comment]
By the way: I confirm that I was able to reproduce the issue you reported. The solution will be to remove the `editorType` parameter from the `UpdateVersionAsync` method.

**Comment by Jericho** [comment]
Version 0.59.0 is being published right now. Should be available on NuGet shortly.
