### ISSUE TITLE
Updating contacts in bulk

### ISSUE THREAD

**Issue by kbtahir** [Jericho/StrongGrid#293]
I just tested this library and the create contacts functionality and it works great.

Is there a way to send multiple contacts at once?  According to the sendgrid API documentation, it supports upto 1000 contacts per call.

https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Add-Multiple-Recipients-POST

I have a requirement to update over 100K contact profiles on a daily basis and want to do this in an efficient way.

Thanks!

**Comment by Jericho** [comment]
You can send multiple contacts in a single call by invoking the `Contacts.ImportAsync` method. This method will create new contact records and also update existing records as well.

**Comment by kbtahir** [comment]
Brilliant!  Sorry I missed that and thanks for the prompt reply.

Great work on this library!
