### ISSUE TITLE
Possible bug when sending attachments

### ISSUE THREAD

**Issue by spib** [Jericho/StrongGrid#298]
Hi

We recently upgraded to v0.60.0 and have since found that when sending an attachment, only the first 4KB of data is included. Reverting to version 0.59.0 fixes the issue.

Below is an example which recreates the issue

    var client = new Client("my_api_key");
    var a = new System.Net.Mail.Attachment(@"C:\FileLargerThan4KB.pdf");

    client.Mail.SendToSingleRecipientAsync(new MailAddress("james@somedomain.com", "James Spibey"),
				new MailAddress("james@somedomain.com", "James Spibey"),
				subject: "Test",
				htmlContent: "Some html",
				"Some text",
				attachments: new Attachment[]
				{
					Attachment.FromStream(a.ContentStream, a.Name)
				});

Let me know if I can help any further

Thanks

**Comment by Jericho** [comment]
I did all my testing with rather small files so I never notice a problem. I will try with larger files and see if I can reproduce (it probably won’t be before the weekend though). 

In the mean time, let’s eliminate the System.Net.Mail.Attachment class as a possible source of the issue with the following code:

attachments: new Attachment[]
			{
				Attachment.FromLocalFile(@“C:\FileLargerThan4KB.pdf");
			});

**Comment by spib** [comment]
Thanks, I can confirm that the same problem occurs when using Attachment.FromLocalFile

**Comment by Jericho** [comment]
Ok. Thanks for confirming.

**Comment by Jericho** [comment]
I just tested sending myself an email with a larger attachment and I am not noticing the same problem you are reporting.

I receive the email with the attachment as you can see here:
![image](https://user-images.githubusercontent.com/112710/65201112-656a8380-da57-11e9-8bc8-7cd0cbc3363e.png)

but when I attempt to open the attachment, I get the following error:
![image](https://user-images.githubusercontent.com/112710/65201133-7f0bcb00-da57-11e9-90bc-114f306fdb56.png)

So there indeed seems to be a problem, but it doesn't seem to be the same as what you are experiencing.

**Comment by Jericho** [comment]
I will raise another issue to track the issue I discovered but I will need more guidance from you to reproduce the issue you are experiencing.

**Comment by spib** [comment]
Hey @jericho let me know what info you need and I’ll help however I can

**Comment by Jericho** [comment]
I meant to ask you: what makes you say that only the first 4KB is included? Is it because Outlook (or your email client of choice) says the attachment is 4KB?

Anyway, I'll publish an update to fix the problem I am able to observe and maybe it will also solve the problem you are experiencing???

**Comment by Jericho** [comment]
0.61.0 published. Let me know if it solves the issue.

**Comment by spib** [comment]
> 0.61.0 published. Let me know if it solves the issue.

Yep, that seems to havve fixed it! Thanks for the quick response
