### ISSUE TITLE
Async ParseInboundEmailWebhook support

### ISSUE THREAD

**Issue by cloudb0x** [Jericho/StrongGrid#300]
With .Net core 3 synchronous  IO is disabled by default , in order to parse an inbound mail I have to enable it on startup.

Is there plans to add an async version of the `ParseInboundEmailWebhook` method ?

**Comment by Jericho** [comment]
I did not consider making `public InboundEmail ParseInboundEmailWebhook(Stream stream)` async because all the code in this method executes synchronously. but now that you have pointed out that it causes some friction in .net core 3, I might revisit this decision.

**Comment by cloudb0x** [comment]
I would be happy to take a look at it and perhaps implement an async implementation for you to review?

**Comment by Jericho** [comment]
Sure, but let me point out that the IO occurs in a [third-party nuget package](https://www.nuget.org/packages/HttpMultipartParser/) that StrongGrid relies on. Their github project is [here](https://github.com/Vodurden/Http-Multipart-Data-Parser). Therefore, in order to ensure `ParseInboundEmailWebhook` is async, you should probably investigate making that project 'async-friendly'.

**Comment by cloudb0x** [comment]
Will have a peek around the codebase. Atleast this thread can serve as a point of reference for anyone googling the same issue.

**Comment by Jericho** [comment]
@cloudb0x I am taking over maintenance of the project that StrongGrid depends on. One of the first improvement I will take care of is to [add async version of I/O calls](https://github.com/Vodurden/Http-Multipart-Data-Parser/issues/69). This will ultimately allow me to add async version of parser methods in StrongGrid.

**Comment by cloudb0x** [comment]
@Jericho  thank you - im taking a system to production soon and had to excluded the library due to synchronous operation. Let me know when its pushed and I will merge my branch back in.

**Comment by Jericho** [comment]
@cloudb0x good news: I published a new version of the http multipart data parser which supports async I/O. This means that I am now able to work on a async webhook parser in StrongGrid. Expect a new release shortly.

**Comment by cloudb0x** [comment]
@Jericho  Thanks for the update. Appreciate your hard work!
