### ISSUE TITLE
Add support for Subuser Reputations

### ISSUE THREAD

**Issue by Taigus** [Jericho/StrongGrid#301]
In order to monitor my subusers, I'd like support for /subusers/reputations
Reputation is already available through the Account on the User resource, but access is restricted.

**Comment by Taigus** [comment]
Please see #302

**Comment by Jericho** [comment]
Is this new API functionality that Sendgrid recently added? I read their release notes regularly and I did not see a mention about it.

Anyway, I completely agree that we need to add this feature in StrongGrid.

**Comment by Taigus** [comment]
I don't know when it was added as I don't have much history with their API, but the manual solution I inherited referenced the endpoint as early as November 2018.
The documentation seemed a little sparse, and I wasn't originally very confident about the ability to get more than one subuser's data at a time. Following the pattern for the rest of the API worked in my tests, so I included it.
It might be worth additional testing to verify the 10 item limit for "usernames"
