### ISSUE TITLE
getting marketing template for using in creating a campaign

### ISSUE THREAD

**Issue by kbtahir** [Jericho/StrongGrid#315]
Hi,

I would like to create a campaign using an existing marketing template that is already configured in SendGrid.  Any sample code you can provide is greatly appreciated.

I am trying to create a campaign using the client.Campaigns.CreateAsync method.  It looks like this takes a parameter for the htmlContent.  

How do I get the html from the existing marketing template in order to set the htmlContent parameter in the method above.  I tried to get the template first but nothing is returned when i call the client.Tempaltes.GetAsync method.  Here is what I am trying to do in code:

var template = strongGridClient.Templates.GetAsync("myTemplateName").Result;

string htmlContent = template.Versions[0].HtmlContent;

var task = await strongGridClient.Campaigns.CreateAsync (
"myCampaignName"
,"senderId"
,"subject"
,htmlContent
,,,,)

Thanks
Khurram

**Comment by Jericho** [comment]
You attempt to retrieve a template by passing `myTemplateName` (which sounds like the name of the template to me) to the `Templates.GetAsync` method when this method expects you to provide the unique identifier of the desired template. That's probably why SendGrid is not returning the template.

**Comment by kbtahir** [comment]
Thanks but also when i try to get all templates, nothing is returned.  I tried both legacy and dynamic.  Can you provide any sample code on how to retrieve templates?  Either all or by name?

            Template template = new Template();

            Task getTemplates = Task.Run(async () =>
            {

                Template[] alltemplates = await sendGridClient.Templates.GetAllAsync(TemplateType.Dynamic);

                Console.WriteLine("found {0} templates", alltemplates.Length);

                template = alltemplates.Where(p => p.Name == "pzn_openings").FirstOrDefault();

            });

            getTemplates.Wait();

**Comment by kbtahir** [comment]
Please ignore or close this issue.  I was trying to retrieve marketing templates but it looks like the api only supports transnational templates.
