### ISSUE TITLE
EventType on webhooks event model classes does not default to an appropriate value

### ISSUE THREAD

**Issue by gregveres** [Jericho/StrongGrid#331]
Hi, 

I am writing unit tests for my webhook implementation. I am using this to parse the events:

```
            var parser = new WebhookParser();
            StrongGrid.Models.Webhooks.Event[] events = await parser.ParseWebhookEventsAsync(await Request.Content.ReadAsStreamAsync());
```
and then passing the array of events to the function I am unit testing. In my unit tests, I create a DroppedEvent like this:

```
        private DroppedEvent createDroppedEvent()
        {
            var e = new StrongGrid.Models.Webhooks.DroppedEvent();
            e.UniqueArguments.Add("SC_ID", "12345");
            e.Reason = "dropped event";
            return e;
        }
```

but then when I look at the event.EventType, the debugger says that its value is "Processed". I expected its event type to be "Dropped". Is this a bug.

I just looked at the code and I see that DroppedEvent doesn't have a constructor so it doesn't have a chance to set EventType to Dropped. 

I am going to work around it in my unit test by setting the EventType field but now I don't know if it is going to be set at run time and I am far from being able to test. I guess I could write a unit test to test, but looking at [this code](https://github.com/Jericho/StrongGrid/blob/3657cf0ade154969eb50f4c375747814643f06f4/Source/StrongGrid/Utilities/WebHookEventConverter.cs#L115) it doesn't look like it gets set.

I think it would be very helpful if EventType was set properly. This could be achieved by setting the field appropriately in each default constructor for the event type. Or setting the event type in the WebHookEventConverter after the event is parsed. You already know what it is.

**Comment by gregveres** [comment]
OK, I wrote some unit tests with some data I pulled from our SendGrid account and I see that when doing the parsing, somehow the EventType is getting set. 

So I will make sure that I set the proper event type in my unit tests when I create the particular events given that the ctor doesn't do it.

Now that I know the proper parsing is going to set the event type, I am on the fence of should creating an instance of the event set its type. It would be handy for unit testing, but at the same time, event webhook processing is a time sensitive operation because of the volume of calls, so every savings helps. 

You can fix or close as you see fit.

**Comment by Jericho** [comment]
The JSON posted by SendGrid includes a property that maps to the event type; therefore the `EventType` property is always set to the proper value when a webhook is parsed. 

However, I had not considered scenarios like you describe where you create a new instance of the `DroppedEvent` class for unit testing purposes. To make matters more confusing, as you point out, the `EventType` ends up being set to `Processed` by default simply because that's the first value defined in the `EventType` enum.

I'll look at setting this property to the expected value by default.

**Comment by Jericho** [comment]
@gregveres Thanks again for pointing this out. I am modifying the 11 event model classes to ensure their `EventType` defaults to an appropriate value.
