### ISSUE TITLE
Azure Function 2 .NET Core 3.1 Fails on StrongGrid 0.67 but works on Strong Grid 0.66

### ISSUE THREAD

**Issue by implemental** [Jericho/StrongGrid#334]
On VS2019 Community, running a vanilla 'hello world' type of application with "File/Project/New" Azure 2 Function in .NET Core 3.1 fails at startup with the following message.

[7/27/2020 5:40:37 PM] A host error has occurred during startup operation '5f3e1ad0-accc-4818-b012-5466af777843'.
[7/27/2020 5:40:37 PM] System.Private.CoreLib: **Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.3.0,** Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file.

Attempting to manually reference Microsoft.Extensions.Logging.Abstractions 3.1.3.0 fails. This type of hello world project works on Strong Grid <=0.66, but fails once you migrate nuget to StrongGrid 0.67 or higher.

**Comment by Jericho** [comment]
It's weird that this nuget package is not found in your environment. It's publicly available [on NuGet](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/3.1.3).

When you manually reference the package, do you get a more descriptive message that could help diagnose this problem?

**Comment by Jericho** [comment]
Also, StrongGrid 0.70.0 is the latest. Might be worth upgrading to the latest.

**Comment by implemental** [comment]
I have upgraded to StrongGrid 0.70 with the same issue. I downgraded until I determined that StrongGrid 0.66 works. If you use NuGet to manually reference Microsoft.Extensions.Logging.Abstractions, the error is identical" System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file."

**Comment by implemental** [comment]
Unfortunately, manually referencing the abstractions DLL, without using NuGet, still fails with the exact same error.

**Comment by implemental** [comment]
Ok, I'm going to revisit using an Azure Function 3 to see if this resolves. I believe this is a .net core framework issue and not a StrongGrid issue. I will report back any work arounds.

**Comment by implemental** [comment]
**SOLVED:** In order to solve assembly load issues, I needed the following combination of assets:
Azure Function 3
.NET Core 3.1
StrongGrid 0.70

This removes issues with binding Microsoft.Extensions.Logging.Abstractions
