### ISSUE TITLE
Breaking change: long to string in `StrongGrid.Models.Field`

### ISSUE THREAD

**Issue by mynkow** [Jericho/StrongGrid#335]
The `Id` property type has been changed from long to string in version 0.66.

How this change affects us and how we should migrate?

**Comment by Jericho** [comment]
This model was indeed modified in release 0.66.0. The reason for this change is: SendGrid modified their API. They have a "new" marketing API which StrongGrid supports but we also support their "legacy" marketing API which you can use like this:

```csharp
// This client allows you to use the legacy marketing API
var legacyClient = new LegacyClient(apiKey);
```
