### ISSUE TITLE
SendGrid shutting down port 80 in favour of https:443

### ISSUE THREAD

**Issue by gregveres** [Jericho/StrongGrid#339]
Hi

Did you get a notice today from Twilio that they are shutting down access to http:80 on Oct 1st, 2020? They want to move everybody over to https:443 instead. 

I am pretty sure that the url is embedded in StrongGrid right?

**Comment by gregveres** [comment]
Hmm, I wonder why they think I am using http:80 when I see you set the uri to https
```
		private const string SENDGRID_V3_BASE_URI = "https://api.sendgrid.com/v3";
```
Strange because they claim I have used http in june and july.

**Comment by gregveres** [comment]
I am on version 0.69. I will upgrade to 0.71.

**Comment by Jericho** [comment]
No I did not get any notification but, as you discovered, StrongGrid is already using HTTPS so I think we are safe.

**Comment by gregveres** [comment]
Yea, I am trying to figure out why they think I am communicating over http. I am only using StrongGrid and it clearly uses https. I have opened a support ticket. If something comes back that involves StrongGrid, I will let you know.

**Comment by Jericho** [comment]
Perfect. Thanks for keeping me in the loop.

**Comment by jclimac** [comment]
> Strange because they claim I have used http in june and july.

I have 3 account at Sendgrid, one of them I don't use for months now and i received the same email for all the 3 accounts. I think they send this message for, if not all, almost all clients that used the API no matter if using http or https.

**Comment by Jericho** [comment]
@gregveres I am closing this issue since I don't think there's anything for me to do at this point, but make sure to keep us in the loop if you find out more details about this situation. Thanks.
