### ISSUE TITLE
Facing "Unexpected end of stream" error when trying to parse email with attachment

### ISSUE THREAD

**Issue by arunprasath2007** [Jericho/StrongGrid#340]
Hello - I'm trying to use the latest package of StrongGrid and I'm facing an issue in parsing email with attachment. Error message says ""Unexpected end of stream". Per earlier comment, I tried disabling the "Send Raw" as part of Inbound Parse setting but still the issue remains the same. 

Find below the sample code-

```csharp
static async Task SendGridParseTest()
{
  var fs = new FileStream("emailtext.txt", FileMode.Open, FileAccess.Read);
  var parser = new WebhookParser();
  try
  {
    var events = parser.ParseInboundEmailWebhook(fs);
  }
  catch (Exception ex)
  {
    var exm = ex.Message;
  }
  Console.ReadKey();
}
```
Find below the stack trace details...

```
Error Message: "Unexpected end of stream"

Stack Trace:
   at HttpMultipartParser.StreamingMultipartFormDataParser.ParseSection(RebufferableBinaryReader reader)
   at HttpMultipartParser.StreamingMultipartFormDataParser.Parse(RebufferableBinaryReader reader)
   at HttpMultipartParser.StreamingMultipartFormDataParser.Run()
   at HttpMultipartParser.MultipartFormDataParser.ParseStream(Stream stream, String boundary, Encoding encoding, Int32 binaryBufferSize)
   at StrongGrid.WebhookParser.ParseInboundEmailWebhook(Stream stream)
   at BLR.MailjetPOC.Program.<SendGridParseTest>d__14.MoveNext() 
```

I'm also attaching the debug details, email that was received from Sendgrid. let me know if you need any additional details to review this issue? 

![image_2020_08_29T14_32_17_340Z](https://user-images.githubusercontent.com/1463927/91639368-b9d1fd80-ea33-11ea-8bf3-1c35d40a0b70.png)

[emailtext.txt](https://github.com/Jericho/StrongGrid/files/5145414/emailtext.txt)

**Comment by Jericho** [comment]
I just opened the text file you attached to your question and I notice the following:
![image](https://user-images.githubusercontent.com/112710/91641368-d2212880-e9f1-11ea-8c08-47209d2cc18b.png)

This doesn't seem right to me. Looks like the PDF content was truncated.

**Comment by arunprasath2007** [comment]
Hello - Thanks for getting back! Yes, you're right, I assume the conversion from Sendgrid email doesn't seem to be working right. I'm going to investigate further and will get back to you. lets close this for now. Thanks again for developing such a great API!
