### ISSUE TITLE
Retrieve the reason for a deferred event received from webhook

### ISSUE THREAD

**Issue by philippedurocher** [Jericho/StrongGrid#343]
Hi,

how can I retrieve the reason for a deferred event received from webhook? I'm trying to understand but can't figure it out.

Thank you for the time and efforts you put in your project.

**Comment by Jericho** [comment]
Are you usgin the `ParseEventsWebhookAsync` (or its non-async equivalent, `ParseEventsWebhook`) method of the WebhookParser class to parse the stream posted by SendGrid? 

If so, this method returns an array of strongly typed events of various types such as BounceEvent, DroppedEvent, DeliveredEvent, etc. and also `DeferredEvent`. This type has a property called `Reason` which should give you the information you are looking for.

Let me know if this helps.

**Comment by philippedurocher** [comment]
```
var events = await parser.ParseEventsWebhookAsync(Request.Body).ConfigureAwait(false);
foreach (var e in events)
{
	// Do something here with each event
}
```

And inside foreach like this?
```
if (e.EventType == StrongGrid.Models.EventType.Deferred)
{ 
	string reason = ((DeferredEvent)e).Reason;
}
```

**Comment by Jericho** [comment]
Yes that should work.
