### ISSUE TITLE
Reason is always null for Deferred event type

### ISSUE THREAD

**Issue by philippedurocher** [Jericho/StrongGrid#344]
Hi, here is the code I'm using to obtain events reason/response messages

```
case StrongGrid.Models.EventType.Dropped:
					message = ((StrongGrid.Models.Webhooks.DroppedEvent)e).Reason;
					break;

case StrongGrid.Models.EventType.Delivered:
					message = ((StrongGrid.Models.Webhooks.DeliveredEvent)e).Response;
					break;

case StrongGrid.Models.EventType.Deferred:
					message = ((StrongGrid.Models.Webhooks.DeferredEvent)e).Reason;
					break;

case StrongGrid.Models.EventType.Bounce:
					message = ((StrongGrid.Models.Webhooks.BouncedEvent)e).Reason;
					break;
```

Reason in DeferredEvent is always null but Response/Reason from other events are working fine.  Do you have any idea why?

Thank you!

**Comment by Jericho** [comment]
Did you inspect the JSON received from SendGrid? Can you post it here so I take a look at it. My guess is that SendGrid is probably omitting this information but I won’t know for sure until I can look at the json they send to you.

**Comment by philippedurocher** [comment]
![image](https://user-images.githubusercontent.com/1459389/93624267-1890f400-f9ae-11ea-963a-2817ff434448.png)

My guess is that for an event deferred it should be response instead of reason?

**Comment by Jericho** [comment]
you're probably right, but this contradicts SendGrid's documentation. It wouldn't be the first time their documentation is wrong!

**Comment by philippedurocher** [comment]
https://sendgrid.com/docs/for-developers/tracking-events/event/#delivery-events

![image](https://user-images.githubusercontent.com/1459389/93727935-99591700-fb8b-11ea-8bd5-968bc6ac44e3.png)

**Comment by Jericho** [comment]
https://sendgrid.com/docs/for-developers/tracking-events/event/#event-objects

**Comment by Jericho** [comment]
I raised an issue in SendGrid's documentation repo ([here](https://github.com/sendgrid/docs/issues/6251)) asking for clarification. 

By the way, their documentation for the various webhook events is notoriously inconsistent an inaccurate so I'm not surprised you found an issue. I have raised several issues over the years about this:

- https://github.com/sendgrid/docs/issues?q=is%3Aissue+author%3AJericho+
- https://github.com/sendgrid/sendgrid-csharp/issues/792
- https://github.com/Jericho/StrongGrid/issues/247
- https://github.com/Jericho/StrongGrid/issues/314

**Comment by Jericho** [comment]
While we wait for clarification from SendGrid, I have a suggestion:

1. Add a `Response` property to the DeferredEvent class since we strongly suspect this is the correct property
2. Leave the `Reason` property in case it may be correct but mark it as 'obsolete' with a message to let developers know that we suspect this property is incorrectly documented.

Something like this:
```csharp
[JsonProperty("reason", NullValueHandling = NullValueHandling.Ignore)]
[Obsolete("We believe this field is not included in the webhook data posted by SendGrid (despite what their documentation says). Use the 'Response' field instead.")]
public string Reason { get; set; }

/// <summary>
/// Gets or sets the full text of the HTTP response error returned from the receiving server.
/// </summary>
/// <value>
/// The response.
/// </value>
[JsonProperty("response", NullValueHandling = NullValueHandling.Ignore)]
public string Response { get; set; }
```
