### ISSUE TITLE
ParseInboundEmailWebhookAsync encoding question

### ISSUE THREAD

**Issue by ThomasDoyle-byte** [Jericho/StrongGrid#348]
ParseInboundEmailWebhookAsync sets the encoding for "html" and "text" to us-ascii, I was expecting it to detect the encoding as utf-8.

Example email text:
This is a test email with ññ ñññ ññ basic HTML formatting

After parsing it displays as:
This is a test email with ?? ??? ?? basic HTML formatting

**Comment by Jericho** [comment]
Correct me if I'm wrong, but this issue appears to be a duplicate of #347
