### ISSUE TITLE
Add unofficial support for /v3/suppression/unsubscribes?email=some-text

### ISSUE THREAD

**Issue by jsgoupil** [Jericho/StrongGrid#364]
Their API does not mention that this is possible on this page `GET
/suppression/unsubscribes` to add an email query.

However, their Sendgrid UI makes that request by adding `email=` to the query string.

Without this, getting the metadata of `created` returned by this API is less than easy because this API has a limit/offset.

**Comment by Jericho** [comment]
I just tested and you are right: this is not documented but it works as you describe. 

One weird quirk I noticed: despite the fact that we request only one specific address, the response contains an array but this array contains one single item. That's weird but not a big problem, I can definitely hide this quirk and make sure to return only the requested record.

Something like this:
```csharp
/// <summary>
/// Get all globally unsubscribed email addresses.
/// </summary>
/// <param name="email">The email address to retrieve.</param>
/// <param name="onBehalfOf">The user to impersonate.</param>
/// <param name="cancellationToken">The cancellation token.</param>
/// <returns>
/// The <see cref="GlobalSuppression"/>.
/// </returns>
Task<GlobalSuppression> GetAsync(string email, string onBehalfOf = null, CancellationToken cancellationToken = default);
```

**Comment by jsgoupil** [comment]
@Jericho I think the limit and offset still has a good place there when searching with the email. Technically you can put "gmail.com" there and still receive a long list of data.

**Comment by Jericho** [comment]
I didn't know that you could search for a domain... because it's not documented!!!! I thought you could only request one specific address. I'll adjust accordingly.

Anything else you figured out that I should take into consideration?

**Comment by jsgoupil** [comment]
Ah, I didn't know they had a SendGrid/docs github! But as you said, I don't think much will happen there unfortunately.

I handled sub-users, authenticated domains, api keys, templates and on-behalf-of.
So far, other than being frustrated with SendGrid, I didn't find anything else to improve this library. I opened a support request about `GET /v3/whitelabel/domains/{id}` that is cached for 10 minutes; giving me stale data.

Also, some error 500 being sent when creating an API key to the sub-user but the parent API key does not have the child permission.

Thanks for your library :)

**Comment by jsgoupil** [comment]
The `email`, you can search for anything. One letter.

**Comment by Jericho** [comment]
hummmm. I am not observing the same behavior. I am indeed able to search for one specific address
```
REQUEST: GET https://api.sendgrid.com/v3/suppression/unsubscribes?email=example%40example.com&limit=50&offset=0 
RESPONSE: [{"created":1611077899,"email":"example@example.com"}]
```

but searching for "example.com" returns nothing:
```
REQUEST: GET https://api.sendgrid.com/v3/suppression/unsubscribes?email=example.com&limit=50&offset=0
RESPONSE: []
```

**Comment by Jericho** [comment]
UPDATE: I am able to search using only the 'example' domain without '.com':
```
REQUEST: GET https://api.sendgrid.com/v3/suppression/unsubscribes?email=example&limit=50&offset=0
RESPONSE: [{"created":1611077899,"email":"example@example.com"},{"created":1611077899,"email":"example2@example.com"}]
```

I'm guessing it's an encoding problem? I'll try to figure out how the search term should be encoded.

**Comment by jsgoupil** [comment]
You are correct. Wrong assumptions, however look at this one as well.

```
GET /v3/suppression/unsubscribes?offset=0&limit=50&email=jsgoupil

[{"created":1611078349,"email":"jsgoupil@gmail2.com"},{"created":1611078323,"email":"jsgoupil@gmail3.com"}]
```

It works if you put a full username. But I try to search for `gmail` or `gmail2` and it doesn't work.
I think you could simply allow anything to be passed in the "email" and return an array.

**Comment by Jericho** [comment]
In your case it returns nothing if you search for `gmail2`??? I would have expected that it would return one address. This is most bizarre?!?!?!?

**Comment by Jericho** [comment]
I just realized that in my case "example" is both the user name and the domain: `example@example.com` 

That's why my search worked!

**Comment by Jericho** [comment]
Good news: I cleaned up my sample data by making sure the usernames are different than the domains and my search results are now consistent with your results.

So my conclusion is that SendGrid allows us to search for username, even partial search terms are accepted as long as they are at least 3 characters long like `jsgou` for example, but you cannot search for domains like `gmail` or `hotmail` for example.

**Comment by jsgoupil** [comment]
It's a "typeahead" thing. You can't search for `goupil`. I think it has to be starting with.

**Comment by Jericho** [comment]
You're probably right about the "typeahead".

Instead of adding a new method like I suggested earlier, I could simply add a new `searchTerm` parameter to the existing `GetAllAsync` method like this:

```csharp
/// <summary>
/// Get all globally unsubscribed email addresses.
/// </summary>
/// <param name="startDate">The start date.</param>
/// <param name="endDate">The end date.</param>
/// <param name="searchTerm">The search term.</param>
/// <param name="limit">The limit.</param>
/// <param name="offset">The offset.</param>
/// <param name="onBehalfOf">The user to impersonate.</param>
/// <param name="cancellationToken">The cancellation token.</param>
/// <returns>
/// An array of <see cref="GlobalSuppression"/>.
/// </returns>
Task<GlobalSuppression[]> GetAllAsync(DateTime? startDate = null, DateTime? endDate = null, string searchTerm = null, int limit = 50, int offset = 0, string onBehalfOf = null, CancellationToken cancellationToken = default);
```

I also will add the following remark based on what you and I discovered:
```csharp
/// <remarks>
/// After much trial and error, we came to the conclusion that SendGrid allows you to search
/// for addresses that "begin with" your search term. So, if you have two email addresses on
/// your global suppression list like user1@hotmail.com and user2@gmail.com, you will be able
/// to search for 'user1', or 'user2' or even 'user' (SendGrid requires that your search term
/// contain at least three characters) but you cannot search for 'hotmail' or 'gmail'.
/// </remarks>
```

**Comment by Jericho** [comment]
If you want to try the new search functionality: https://www.myget.org/feed/jericho/package/nuget/StrongGrid/0.76.0-search-global-su0058

**Comment by jsgoupil** [comment]
Yep, tried it and it works.
