### ISSUE TITLE
Incompatibility with Azure Functions v3 because of dependency on Microsoft.Extension.Logging v5

### ISSUE THREAD

**Issue by kekonn** [Jericho/StrongGrid#370]
I want to use your library in an Azure function to parse an incoming email webhook.

However, at runtime I get an error from the Azure simulator that it has a problem loading Microsoft.Extensions.Logging.Abstractions. 

Currently Azure Functions still run in .NET Core 3.1 and .NET 5 support will not arrive anytime soon. Can you please choose a lower version of that package as a dependency? I suggest version 3.1.11

**Comment by Jericho** [comment]
I'm willing to entertain choosing a different version of dependency but first I would like to understand what problem we are trying to solve. Do you have any error message you can share? Screenshots? Logs?

Also, what led you to conclude there's an issue with this particular dependency which would be related to .net5? As far as I know, this dependency targets net461 and netstandard2.0 and, similarly, StrongGrid targets net461, net472 and netstandard2.0 so net5 shouldn't have anything do with anything.

**Comment by kekonn** [comment]
When I list all the dependencies in the package manager I notice this:
![afbeelding](https://user-images.githubusercontent.com/149670/107114418-fb2dcb00-6865-11eb-8dcf-af15200e6ba9.png)

Then at runtime, without even calling any code from StrongGrid, I get this error:
![afbeelding](https://user-images.githubusercontent.com/149670/107114439-20bad480-6866-11eb-9e05-d2dbed067071.png)

```
[2021-02-06T09:28:25.456Z] System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Het systeem kan het opgegeven bestand niet vinden.
[2021-02-06T09:28:27.792Z] A host error has occurred during startup operation '05845ce1-a26c-40ca-ae7f-794ee4776576'.
```

Some .NET 5 packages are actually .NET Standard 2.0 compatible I guess.

**Comment by Jericho** [comment]
The red arrows in your first screenshot point to the package version, not the version of .net that it targets. The fact that the version of `Microsoft.Extension.Logging` and `HttpMultipartParser` is `5.0.0` is a coincidence but it doesn't mean that these two packages target .net5. If the number in parenthesis represented the targeted version of .net, it would mean that `MimeTypesMap` targets `.net 1.0.8` and `Newtonsoft.Json` targets `.net 11.0.1` which doesn't make any sense!!!

![image](https://user-images.githubusercontent.com/112710/107120559-4e028500-685c-11eb-96aa-931a6c88b497.png)

The second screenshot you provided shows a log which includes the following exception: `Value cannot be null (parameter 'provider')`. This seems more likely to be the problem. We need to figure out why you are getting this error.

Have you been able to reproduce this problem locally? Have you figured out the steps to reproduce the problem? Maybe you could share your C# code and I could help attempt to reproduce.

**Comment by kekonn** [comment]
I seem to have you focused on .NET 5 because of my earlier comment, but forget about that. As I closed my last post with: this error occurs when targetting .NET 5.

The problem is that the Azure functions SDK needs a lower version of the Microsoft.Extensions.Logging package (namely 2.1.0). These two versions conflict with each other confusing the IoC container of the Azure Functions SDK. I'm hesitant to share the project since it contains connection strings to my Azure account.

**Comment by Jericho** [comment]
So the issue is simply due to version mismatch???

Can you setup binding redirection in Azure functions? (I'm not familiar with Azure function).

**Comment by kekonn** [comment]
Not sure. I am not familiar with binding redirections. It is not so much a version mismatch as that there are two different versions of the same assembly being loaded.

**Comment by kekonn** [comment]
@Jericho apparently binding redirection is a .NET framework only thing. It does not apply to .NET Core or .NET Standard.

I also cannot seem to find an alternative.

**Comment by kekonn** [comment]
https://github.com/Azure/Azure-Functions/issues/1729 It seems to be an issue with Azure functions. So I closed the issue because I don't think this is on you to fix. Downgrading to 0.75 of StrongGrid fixed the issue for me.

**Comment by Jericho** [comment]
Thanks for linking the thread on the Azure functions repo. Very interesting.
