### ISSUE TITLE
Get the last message in a reply thread (parse inbound email webhook)?

### ISSUE THREAD

**Issue by CetkoS** [Jericho/StrongGrid#371]
Hello, 
Does anybody know is it possible to divide actual message from others in a reply thread? 

Here is example:  
var inboundEmail = parser.ParseInboundEmailWebhook(stream);
inboundEmail.Html - contains all messages from a email thread - I would like to take only the new(last) one.

**Comment by Jericho** [comment]
I have never had to do this, but sounds like you're not the only one: https://stackoverflow.com/questions/278788/parse-email-content-from-quoted-reply

**Comment by CetkoS** [comment]
Thank you, for response.

I Investigated network there are many solutions/suggestions - but not standard for that. Yes, you are right seems like a lot of people need this functionality.

I just wonder is that already implemented in StrongGrid - so feel free to close question.
