### ISSUE TITLE
Survey: which .Net framework should StrongGrid support (2021 edition)?

### ISSUE THREAD

**Issue by Jericho** [Jericho/StrongGrid#379]
I conducted a similar survey in [2018](https://github.com/Jericho/StrongGrid/issues/219) and [2019](https://github.com/Jericho/StrongGrid/issues/273) and I feel it's time to once again review the frameworks that we currently target and see if any changes are necessary. I'm looking for feedback, so please comment below.

StrongGrid currently targets `net461`, `net472` and `netstandard2.0` and I intend to target net5.0 as well (see #378) but I'm wondering if we could completely drop support for "full" framework (i.e. net461 and net472)? Is that too disruptive though? Is anybody still using the "full" framework? Maybe replacing these two targets with net48 would be a less disruptive approach?

As far as .NET "core", Microsoft has dropped support for 2.0 in October 2018 and 2.1 is the current version under "long term support (see [here](https://dotnet.microsoft.com/platform/support/policy/dotnet-core)). Support for 2.0 ended about 2 and a half years ago so I am pretty confident that developers had enough time to upgrade by now.

I'm trying to strike a balance between supporting the greatest number of developers (no matter which version of the .NET they target) and getting rid of older, unsupported versions of .NET. 

What I'm thinking about doing is:
- remove `net461`, `net472` and replace them with `net48`
- remove `netstandard2.0` and replace it with `netstandard2.1`

Let me know what you think.

Edit: here's an [interesting article](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/) on this topic.

**Comment by Jericho** [comment]
Note to self: reference to `System.Security.Cryptography.Cng` NuGet package and code that relies on EdsaCng encryption in WebhookParser can be removed when we drop support for `net461`.

**Comment by terrysmith-fiworks** [comment]
The net48 option would be great for us. We can't yet make everything netstandard2.1 due to other dependencies.

**Comment by Jericho** [comment]
Thank you for the feedback. You are confirming that I can't drop .NET "full" framework just yet. I will wait a little longer to allow other developers to give their feedback but if I don't hear any objection, I intend to go ahead with my plan to drop net461 and net472 and to move on to net48.

**Comment by Jericho** [comment]
This will be addressed in release 0.80.0
