### ISSUE TITLE
send mail settings: bypass_spam_management vs. SpamChecking

### ISSUE THREAD

**Issue by tmacht** [Jericho/StrongGrid#391]
How does the SpamChecking property of the MailSettings of the SendToSingleRecipientAsync method relate to the bypass_spam_management described here? https://sendgrid.api-docs.io/v3.0/mail-send/v3-mail-send

Because it seems that StrongGrid sends spam_check to SendGrid whereas the SendGrid documentation expects bypass_spam_management. Also, bypass_spam_management only has one field (enable), but SpamChecking has 3 (Enabled, PostToUrl, Threshold).

Thanks for all the good work!

**Comment by Jericho** [comment]
I suspect SendGrid made some changes to their API at some point which would explain the discrepancy between the settings available in StrongGrid and the documentation you linked.

I searched their knowledge center and found an [announcement](https://sendgrid.com/docs/release-notes/#13-th-january-2020) dated January 2020 where they say they are retiring sparsely used mail settings including "Spam Checker". The announcement is not very detailed but I'm guessing the spam checker they mention corresponds to the spam checking property of the MailSettings in StrongGrid. The announcement doesn't mention anything about the new `bypass_spam_management` though.

I also found a page in their documentation that describes the [Spam Checker settings](https://sendgrid.com/docs/ui/account-and-settings/mail/#spam-checker) that StrongGrid implements (i.e.: the enabled property, the threshold and the post URL) and it too alerts the reader that "this settings has been removed". No word on the new `bypass_spam_management` either.

I continued my research and found a December 2020 [pull request](https://github.com/sendgrid/docs/pull/6375/files) in their documentation GitHub repo that adds documentation for "Bypass suppressions" (including `bypass_spam_management`). The section of the PR that is of interest to us corresponds to [this page](https://sendgrid.com/docs/ui/sending-email/index-suppressions/#bypass-suppressions) in their knowledge center.

My conclusion, based on the information I found and presented above, is that they made two changes to their API: 
- in early 2020 they removed the "Spam Checker" settings 
- in late 2020 they added "bypass suppression" settings.

I try to stay up to date with the changes they make to their API but, as you can see, it's not easy! Anyway, thanks for alerting me, I will 

I will make the necessary changes in StrongGrid and I will also double check it there are any other mail settings that have changed.

**Comment by Jericho** [comment]
I just discovered two more changes to SendGrid's mail send API: in [August 2020](https://sendgrid.com/docs/release-notes/#13-th-august-2020), `Sections` and `BCC` mail settings were removed.
