### ISSUE TITLE
Unexpected error: bypass_list_management is mutually exclusive with bypass_bounce_management, bypass_spam_management and bypass_unsubscribe_management

### ISSUE THREAD

**Issue by tmacht** [Jericho/StrongGrid#395]
When I pass the following mailSettings to SendToSingleRecipientAsync I get the error message "bypass_list_management is mutually exclusive with bypass_bounce_management, bypass_spam_management and bypass_unsubscribe_management.".

```
mailSettings: new MailSettings
{
    BypassSpamManagement = true
}
```

Any idea why? Because I think I should only get this error message if bypass_spam_management AND bypass_list_management  were true, but bypass_list_management is false in my example.

**Comment by Jericho** [comment]
This is an interesting situation!?!? 

SendGrid is complaining about the mere presence of bypass_list_management in the JSON payload despite the fact that it's value is set to false. 

I guess SendGrid expects us to omit bypass_list_management (and presumably also the other bypass_xxx_management) when their respective value is true.

I'll double check the docs in case I missed something but I don't remember reading anything about omitting certain settings in some scenarios.

**Comment by tmacht** [comment]
Great, thanks, the error is gone.
