### ISSUE TITLE
sg_machine_open support?

### ISSUE THREAD

**Issue by ServicePal** [Jericho/StrongGrid#405]
Any plans to add support for sg_machine_open in this library?

What do you need to know?

Following Apple’s Mail Privacy Protection (MPP) announcement, we have seen increased email recipient open tracking anonymization. This prevents email senders from seeing how MPP-enabled recipients are engaging with their emails. 

Effective October 12, 2021, Twilio SendGrid will include a “sg_machine_open” field to open events visible through the Event Webhook to identify opens triggered by Apple machines. This machine open field is limited to Apple machine opens.

When the “sg_machine_open” boolean field is set to true, it will indicate that the open event was anonymously triggered by an Apple machine, not a human. 

This addition won’t appear in the SendGrid console and should not disrupt your ability to absorb webhook events. Please refer to Twilio’s blog post, How to Prepare for Apple’s Mail Privacy Protection, to help you prepare for MPP and its impacts.

What do you need to do?
If you want to use this new field in an open event, configure your webhook open event to incorporate the boolean tag “sg_machine_open”.

**Comment by Jericho** [comment]
> Any plans to add support for sg_machine_open in this library?

Sure
