### ISSUE TITLE
Models do not support being serialized / deserialized by JSON.NET

### ISSUE THREAD

**Issue by stephajn** [Jericho/StrongGrid#443]
It would be great if the models could be decorated with JSON.NET based serialization attributes as well so that if someone is using JSON.NET rather than the built in serializer, it can still work the same way.

**Comment by stephajn** [comment]
The JsonPropertyName attribute is only recognized if you use the System.Text.Json.JsonSerializer class.

But if you were to try to use Newtonsoft.Json's JsonConvert class to serialize or deserialize them, then it isn't able to behave the same way.

So imagine I am trying to serialize the DeliveryEvent class using JSON.NET

The source has this in it:

```
[JsonPropertyName("ip")]
public string IpAddress { get; set; }
```

If I was to try to deserialize that class using JSON.NET, the IpAddress property wouldn't be deserialized properly because JSON.NET would be looking for a property called IpAddress in the source string.

JSON.NET has its own attributes for this, so I'd suggest that you might want to decorate all of the properties with both attributes.

```
[JsonPropertyName("ip")]
[Newtonsoft.Json.JsonProperty("ip")]
public string IpAddress { get; set; }
```

That way this class could be serialized and deserialized using both serializers equally.

**Comment by Jericho** [comment]
As I explain in [the other issue](https://github.com/Jericho/StrongGrid/issues/442) your raised, the stated goal of the StrongGrid library is to simplify how you interact with SendGrid's API. Allowing developers to serialize/deserialize data to/from JSON using the serialization of their choice is not a goal of the library. Therefore, I don't intend to add multiple attributes per model class property and/or provide serializer for each of the well-known serialization libraries that developers might want to utilize.

Having said this, I have agreed to implement the improvement you proposed in #442 which will allow you to serialize data to JSON using the same serialization library that StrongGrid uses internally (which is System.Text.Json) and you can revert to version 0.86.0 which was the last version of StrongGrid which used Newtonsoft's JSON serializer.

I hope either one of these suggestions is a suitable alternative.

**Comment by stephajn** [comment]
Makes sense.  Thanks for the clarification!
