### ISSUE TITLE
InboundEmail model missing properties (ParseInboundEmailWebhookAsync)

### ISSUE THREAD

**Issue by Minisaints** [Jericho/StrongGrid#446]
Hi,

I can receive inbound email responses fine but the "Html", "Text" are null. However, the raw email data on the response contains this information.

This is the response I receive below from a standard email send with Outlook with a single CC and a single text file.

[inboundResponse.txt](https://github.com/Jericho/StrongGrid/files/8489965/inboundResponse.txt)

This is the VB API code I'm using too.

```
<HttpPost>
        <Route("email/inbound")>
        Public Async Function InboundEmail() As Threading.Tasks.Task(Of IHttpActionResult)
            Try
                Dim parser = New WebhookParser()
                Dim email = Await parser.ParseInboundEmailWebhookAsync(Request.Content.ReadAsStreamAsync.Result).ConfigureAwait(False)

                Return Ok(JsonConvert.SerializeObject(email))
            Catch ex As Exception
                Return BadRequest(ex.Message)
            End Try

        End Function
```

Am I using the API incorrectly? I can provide more information if needed.

Thanks in advance.

**Comment by Minisaints** [comment]
> 99.999999999% of all problems I have observed with parsing SendGrid webhook data were caused by developers selecting the "RAW" format which can't be parsed by the StrongGrid parser. I might be exaggerating a little bit 😜 but the fact remains that it's the number one source of parsing related issues. So, before we invest time and effort investigating what could be causing the problem you are experiencing, please check, double-check, triple-check that you have NOT requested the raw format. In other words, make sure the "raw format" option is UNCHECKED like in this screenshot:
> 
> ![image](https://user-images.githubusercontent.com/112710/163446809-dd5aa2ee-2419-4918-981f-5dd587eaef78.png)
> 
> Although, typically when developers request the raw format, StrongGrid can't parse the data and throws an exception similar to: “Duplicate field in section”. The fact that you don't seem to be getting an exception makes me suspicious that something else might be going on. But like I said, before we invest time and effort researching this situation I think it's important that you please confirm that you have selected the expected format.

Haha you might actually have a point, I'm pretty sure I have it ticked! I'll double check and confirm if I'm an idiot when I get back. 😥

**Comment by Minisaints** [comment]
I did have the POST raw checkbox enabled and after disabling and a few changes, it's all working fine. 🥳

Thank you.

**Comment by Jericho** [comment]
glad we figure it out!
