### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by mcknight89** [Jericho/StrongGrid#459]
I'm trying to use the new contacts system but ran in to a few issue along the way:

- The examples are for the old system and no longer present under the Contact class. await strongGridClient.Contacts.CreateAsync(email, firstName, lastName, customFields) is now await strongGridClient.Contacts.UpsertAsync(contacts, new string[] { }) which you have to poll the result for, Would be good to get updated examples
- When polling for the result I get an error because an enum is not implemented "System.ArgumentException: 'There is no value in the JobStatus enum that corresponds to 'completed'.'"

Hope this helps someone

**Comment by Jericho** [comment]
Quick note regarding the JobStatus: "completed" is indeed the status that indicates that an import job has finished without errors but "ready" is still the status that indicates that an export job has finished without error.

From SendGrid's documentation for [export job status](https://docs.sendgrid.com/api-reference/contacts/export-contacts-status#responses): `Allowed values: pending, ready, or failure`.
From SendGrid's documentation for [import job status](https://docs.sendgrid.com/api-reference/contacts/import-contacts-status#responses): `Allowed values: pending, completed, errored, or failed`.

StrongGrid currently has only one enum which is used by both export job status and import job status. I'm starting to wonder whether I should create distinct enums for each status (i.e.: ImportJobStatus and ExportJobStatus).

**Comment by Jericho** [comment]
I have raised a [separated issue](https://github.com/Jericho/StrongGrid/issues/460) to track the changes needed to fix the missing job status value.

**Comment by Jericho** [comment]
I updated the code sample to demonstrate how to import contacts. Let me know what you think.
