### ISSUE TITLE
Package StrongGrid 0.82.0 is not compatible with netcoreapp2.2

### ISSUE THREAD

**Issue by g7crservice-sajid-f** [Jericho/StrongGrid#481]
Hi @Jericho, @KoditkarVedant, @mbernier 

Package StrongGrid 0.82.0 is not compatible with netcoreapp2.2

please suggest the exact version for .NET core 2.2

**Note: I know .net core 2.2 is in end of life**

**Comment by Jericho** [comment]
Have you looked at the version history like I mentioned?

**Comment by g7crservice-sajid-f** [comment]
Thanks @Jericho

**Comment by Jericho** [comment]
You're welcome
