### ISSUE TITLE
.Text is empty on many emails

### ISSUE THREAD

**Issue by kevinDVault** [Jericho/StrongGrid#485]
Is there any way to get the .Text only for incoming emails. HTML is always there but many inbound emails don't have anything in the .Text.

We don't want to accept HTML as it's formatting screws up stuff downstream.

**Comment by Jericho** [comment]
Have you looked at the data posted to you by SendGrid to check whether the text is provided? If the text is omitted from the data, that would explain why the .Text property is empty. However, if the text is present, it would probably indicate there's a bug in StrongGrid and we need to investigate.

**Comment by kevinDVault** [comment]
First- Fantastic reponse time. Great stuff.
Let us do some debugging and get some data and I'll post it back here. It's random so we just need to find the right combination that causes it to fail.

thanks

**Comment by Jericho** [comment]
@kevinDVault did you find out additional info about this issue? Did you look at the data you receive from SendGrid as I mentioned last week? If so, can you share this data so I can attempt to reproduce your scenario?

**Comment by Jericho** [comment]
@kevinDVault I never heard back from you so I will assume you were able to figure out a solution.
