### ISSUE TITLE
custom_args is not working when receiving an inbound parse webhook 

### ISSUE THREAD

**Issue by ds21194** [Jericho/StrongGrid#494]
When sending an email to a customer, I'm using personalization as:
```
{
    "personalizations": [
        {
            "to": [..],
            "dynamic_template_data": {..},
            "custom_args": {"customer_id": "..."}
        }
    ]
}
```
But when i'm getting the inbound parse back on the webhook I defined, I'm not seeing anywhere the customer_id property, nor custom_args object. I tried to search for some examples on where should I search it on the response or how to debug but didn't find ether. 

Tnx for the help!

**Comment by Jericho** [comment]
If you provide the JSON payload you receive from SendGrid, I'll be able to validate that your custom arguments are processed as expected and provide code sample for you. In the mean time, what I can say is that StrongGrid is designed to add any unknown values received in a webhook to a `Dictionary<string, string>` property called `UniqueArguments`. In the example you provided, "customer_id" would be one such unknown value and therefore should be in this dictionary. There are a few unit tests in the project to verify that this is working as expected but maybe your situation is somehow different. I won't know for sure until you provide your JSON payload.

In case it's helpful: here's how [I suggest you save the JSON payload to a text file](https://github.com/Jericho/StrongGrid/discussions/450#discussioncomment-2677194) which you can subsequently post here

**Comment by ds21194** [comment]
Just realized I made a mistake on the repo, sorry for the troubles. I'm looking for a python lib, not C#. 
silly mistakes happens when you work late : ) closing the ticket. 
I Appreciate it anyways!
