### ISSUE TITLE
`IpAddress.AssignedOn` can be null

### ISSUE THREAD

**Issue by jsgoupil** [Jericho/StrongGrid#506]
This property can be null.
I get an error when calling `IpAddresses.GetAllAsync`

![image](https://github.com/Jericho/StrongGrid/assets/808649/513c1c79-142f-4191-81b3-4773bd7386ed)

**Comment by Jericho** [comment]
You're right, and SendGrid's documentation agrees with you too:
![image](https://github.com/Jericho/StrongGrid/assets/112710/cc8b6415-0486-4997-866e-bc4496c7a41f)
