### ISSUE TITLE
Vulnerabilities Detected

### ISSUE THREAD

**Issue by drma-tech** [Jericho/StrongGrid#509]
![image](https://github.com/Jericho/StrongGrid/assets/12803050/0dec015b-3b61-4d70-b00e-e8a68944d418)

**Comment by Jericho** [comment]
StrongGrid does not take a direct dependency on any of the three packages on the screenshot you provided. Maybe one of our dependencies does? But which one????

**Comment by Jericho** [comment]
oh and by the way, what lead you to conclude that these dependencies came from StrongGrid in the first place?

**Comment by drma-tech** [comment]
![image](https://github.com/Jericho/StrongGrid/assets/12803050/68d22dea-ef1b-4acc-b383-954f650fb0ce)
![image](https://github.com/Jericho/StrongGrid/assets/12803050/182e8544-5209-4572-a15e-e5df93a14f3d)
![image](https://github.com/Jericho/StrongGrid/assets/12803050/d4a66966-26ee-405c-b211-645ff7f897d2)

**Comment by drma-tech** [comment]
If you open it with Visual Studio, you can easily see this, including where the references come from.

**Comment by Jericho** [comment]
As it turns out, all three references are being pulled in by our dependency on Pathoschild.Http.FluentClient:

![image](https://github.com/Jericho/StrongGrid/assets/112710/8bbefa43-cf32-4868-86a6-ea57219ef6e5)

**Comment by drma-tech** [comment]
im using .net 8.0.  not sure if is using this netstandard

**Comment by drma-tech** [comment]
so, its just notify the owner of this component

**Comment by Jericho** [comment]
When I open the FluentHttp project in Visual Studio and look at their dependencies, I see this:

![image](https://github.com/Jericho/StrongGrid/assets/112710/f2f3c857-1059-4eeb-a7bb-9c072737a5a6)

So, while the author of the FluentHttp project might be able to fix the System.Net.Http reference (by dropping support for netstandard1.x, I presume), the other two are being pulled in by even further upstream dependencies.

**Comment by Jericho** [comment]
Turns out, I was wrong about one specific detail: the FluentHttpClient project is already referencing the patched System.Net.Http package (which is version 4.3.4) as evidenced by:

![image](https://github.com/Jericho/StrongGrid/assets/112710/9b3df141-d663-4b1a-bee7-4ab1bc374c39)

So they may have to go upstream to get this transitive reference upgraded.

**Comment by Jericho** [comment]
FluentHttpClient version 4.4.0 has been released. Upgrading our reference to this new release resolves this warning.
