### ISSUE TITLE
.NET 8 JsonException when trying to parse inbound email

### ISSUE THREAD

**Issue by JLewis1359** [Jericho/StrongGrid#522]
I'm getting the following error when trying to parse an inbound email in the latest version of stronggrid on .Net 8 in an azure functions v4 isolated app.

`System.Text.Json.JsonException: 'The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.'`

Sample Code:

```
var emailParser = new WebhookParser();             
var inboundEmail = await emailParser.ParseInboundEmailWebhookAsync(req.Body).ConfigureAwait(false);
```

I am testing through Postman with a sample email we have using form-data, I have also reverted to our previous build to ensure that the sample email works which it does.

Any help would be appreciated, if you need more info I can provide.

Thanks

**Comment by Jericho** [comment]
The error message is: `The input does not contain any JSON tokens`. 

This seems to indicate there's something unusual about the content that we attempt to parse into JSON. Therefore, the first thing to do is a sanity check on the payload you receive from SendGrid. Does this payload contain a properly formatted JSON string? Is the content empty by any chance? If you post this payload here, I'll be able to look at it.

Another possibility is that you may read the content of the `req.Body` stream (presumably for debugging reasons) which would cause the stream pointer to be moved to the end of the stream and therefore by the time the StrongGrid parser tries to read the content of the stream, all that's left is an empty string (which would explain why the JSON parser complains the content "does not contain any JSON tokens"). If that's the case, you need to make sure to "rewind" the pointer to the beginning of the stream before you ask the StrongGrid parser to parse the body of the webhook.

**Comment by JLewis1359** [comment]
We tried resetting the steam pointer back to the beginning but it still resulted in the same error message above.

Here is the payload that is sent from Postman:

`----------------------------072434111360307773430298
Content-Disposition: form-data; name="headers"


----------------------------072434111360307773430298
Content-Disposition: form-data; name="dkim"


----------------------------072434111360307773430298
Content-Disposition: form-data; name="content-ids"

1
----------------------------072434111360307773430298
Content-Disposition: form-data; name="to"

test@test.com
----------------------------072434111360307773430298
Content-Disposition: form-data; name="text"


----------------------------072434111360307773430298
Content-Disposition: form-data; name="html"


----------------------------072434111360307773430298
Content-Disposition: form-data; name="from"

test1@test.com
----------------------------072434111360307773430298
Content-Disposition: form-data; name="sender_ip"


----------------------------072434111360307773430298
Content-Disposition: form-data; name="spam_report"


----------------------------072434111360307773430298
Content-Disposition: form-data; name="envelope"


----------------------------072434111360307773430298
Content-Disposition: form-data; name="attachment1"; filename="Order.xml"
Content-Type: application/xml

<?xml version="1.0" encoding="utf-8"?>
<cXML>
	<Request>
		<OrderRequest>
			<OrderRequestHeader DeliveryNo="0080601471" DeliveryDate="2022-10-07">
				<SoldTo>
					<Address addressID="0009016700">
						<Name xml:lang="EN">Test Company</Name>
						<PostalAddress>
							<DeliverTo>Test Company</DeliverTo>
							<Street1>Test Street 1</Street1>
							<Street2>Test Street 2</Street2>
							<Street3>Test Street 3</Street3>
							<Street4>Test Street 4</Street4>
							<Street5/>
							<City>Test City</City>
							<PostalCode>123456</PostalCode>
							<Country>Test Country</Country>
						</PostalAddress>
						<Email>test2@test.com</Email>
						<Phone>
							<TelephoneNumber>
								<CountryCode isoCountryCode="TST"/>
								<AreaOrCityCode/>
								<Number>0123 456789</Number>
							</TelephoneNumber>
						</Phone>
					</Address>
				</SoldTo>
				<ShipTo>
					<Address addressID="0009016700">
						<Name xml:lang="EN">Test Company</Name>
						<PostalAddress>
							<DeliverTo>Test Company</DeliverTo>
							<Street1>Test Street 1</Street1>
							<Street2/>
							<Street3/>
							<Street4/>
							<Street5/>
							<City>Test City</City>
							<PostalCode>123456</PostalCode>
							<Country/>
						</PostalAddress>
						<Email>test3@test.com</Email>
						<Phone>
							<TelephoneNumber>
								<CountryCode isoCountryCode="TST"/>
								<AreaOrCityCode/>
								<Number>0123 456789</Number>
							</TelephoneNumber>
						</Phone>
					</Address>
				</ShipTo>
				<BillTo>
					<Address addressID="0000009016">
						<Name xml:lang="EN">Test Company</Name>
						<PostalAddress>
							<DeliverTo>Test Company</DeliverTo>
							<Street1>Test Street 1</Street1>
							<Street2>Test Street 2</Street2>
							<Street3>Test Street 3</Street3>
							<Street4>Test Street 4</Street4>
							<Street5/>
							<City>Test City</City>
							<PostalCode>123456</PostalCode>
							<Country>Test Country</Country>
						</PostalAddress>
						<Email>test4@test.com</Email>
						<Phone>
							<TelephoneNumber>
								<CountryCode isoCountryCode="TST"/>
								<AreaOrCityCode/>
								<Number>0123 456789</Number>
							</TelephoneNumber>
						</Phone>
					</Address>
				</BillTo>
				<VATNo VATNo="123456789"/>
				<EORI EORI="123456789"/>
				<PoNo PoNo="123456789"/>
				<DueDate DueDate="2022-10-12"/>
				<ShipCond ShipCond="Test"/>
				<CommEmail CommEmail="test5@test.com"/>
				<SpecInstr SpecInstr=""/>
			</OrderRequestHeader>
			<ItemOut Batch="105100" NetPrice="20.87" quantity="1.0" lineNumber="900001" Material="000000000000001775"/>
		</OrderRequest>
	</Request>
</cXML>
----------------------------072434111360307773430298
Content-Disposition: form-data; name="attachments"

1
----------------------------072434111360307773430298
Content-Disposition: form-data; name="attachment-info"

{
   "attachment1":{
      "filename":"Order.xml",
      "name":"Order.xml",
      "type":"application/xml",
      "content-id":"ii_1562e2169c132d83"
   }
}
----------------------------072434111360307773430298--
`

**Comment by Jericho** [comment]
This payload does not appear to be valid. At first glance I see at least two issues:
- there's a bizarre quote on the very first line. I haven't tested, but I suspect this probably interferes with the StrongGrid parser's ability to auto-detect the section boundary.
- the `envelope` section is empty when in fact it's supposed to contain a string that can be parsed into a JSON object.

Was this seemingly invalid payload really sent to you by SendGrid or is this something that you crafted by hand?
