### ISSUE TITLE
MailSettings.SandboxMode does not serialize properly

### ISSUE THREAD

**Issue by mdaniline** [Jericho/StrongGrid#77]
According to the [v3 docs](https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/sandbox_mode.html), sandbox mode is enabled by adding the following to `mail_settings`:
```
"sandbox_mode": {
    "enable": true
}
```
The problem is that `SandboxModeSettings` has a single property called `enabled`, not `enable`. Hence, attempting to send a mail using sandbox mode returns a [mail_settings.sandbox_mode.enable](http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.mail_settings.sandbox_mode.enable) error.

You can reproduce this error as follows:
```
var client = new Client(apiKey);
var settings = new MailSettings
{
    SandboxMode = new SandboxModeSettings { Enabled = true }
};
await client.Mail.SendToSingleRecipientAsync(to, from, subject, html, text, mailSettings: settings);
```

I haven't tested this with other settings (e.g. spam check, footer, etc) but I believe these will also break as they all have an `enable` property.

**Comment by Jericho** [comment]
You are right about the SandboxMode not serializing correctly. While researching this issue I also confirmed, as you suspected, that other properties of the MailSetting do not serialize properly. Specifically: Bcc, BypassListManagement and SpamChecking. 

As far the Footer property is concerned, I previously raised issue #42 regarding improper serializing and therefore it was fixed some time ago.

**Comment by Jericho** [comment]
Created issues #78 for the Bcc property, #79 for the BypassListMAnagement property and #80 for the SpamChecking property.

**Comment by Jericho** [comment]
What's really confusing is that in some part of the API the property is called "enable" but in other parts it's called "enabled".

**Comment by Jericho** [comment]
Nuget package v0.11.0 published

**Comment by mdaniline** [comment]
Great, thanks!
