### ISSUE TITLE
Ability to specify custom_args when sending an email

### ISSUE THREAD

**Issue by Gekctek** [Jericho/StrongGrid#90]
I cannot find the ability to specify the custom_args json parameter in the root level or in the personalizations that I see in the [Api Docs](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html).

Is there any work around or will this be added?

**Comment by Jericho** [comment]
I couldn't find a working example of the JSON posted to the SendGrid with `custom-args` so I decided to ignore it while I concentrated on the rest of their API.

Their documentation simply says that `custom_args` is a custom object but doesn't provide any example so I wasn't sure how we are supposed to serialize these custom args.

I am certainly willing to add this property but I would need an example.

**Comment by Jericho** [comment]
By the way, that is also the same reason for the `substitutions` to be missing. I couldn't find a working example.

**Comment by Gekctek** [comment]
All i use it for is to set a string id so i know what object the email is
attached to for my application. I believe in their api it was a
dictionary<string, string> in which i would add {"object_id": "{id}"}. In
their code I think the method was sendGridMessage.AddUniqueArgs(new
Dictionary<string, string> { {"object_id": "{id}"}  }); to add it. I
changed it so I am just looking at git for the history of what we used to
do. So i think if custom_args was just a Dictionary<string,string> that
would be perfect

**Comment by Jericho** [comment]
ok, thanks for the example. It sounds simple enough. I'll add it to the next release

**Comment by Jericho** [comment]
Quick question: where does SendGrid append your `object_id`? Do you need a substitution tag somewhere?

**Comment by Gekctek** [comment]
Not sure if I understand the question. It gets put in the custom_args as
{"object_id", "1"} when I send the message. Then when I get an update on
the status to the email I can read the object I'd from the status update
web hook response

**Comment by Jericho** [comment]
I see. So it's not included in the actual email that is sent to the recipient.

I was trying to test the changes I made and, although SendGrid accepts my JSON with the custom_args, I could not see the values anywhere so I couldn't figure out if it worked or not. Based on what you said, I understand that the test is to read the object and verify the custom_args are present. Got it! Thanks. 

I will have an updated nuget package tomorrow with `substitutions` and `custom_args` and also while testing I discovered that `headers` and `sections (which are similar enumerations of key/value pairs) are not serialized properly and cause an exception. This will be fixed as well.

**Comment by Gekctek** [comment]
Correct just send grid meta data from what I understand. Cool. Thanks for
the fast response

**Comment by Jericho** [comment]
Here's an example I just sent with three custom args:

![image](https://cloud.githubusercontent.com/assets/112710/20699013/8e98ac96-b5ca-11e6-8163-1913c311ec2f.png)

I had never used custom args before so I had to learn how they work, thanks for your help! I'll conform tomorrow when the package is published.

**Comment by Jericho** [comment]
Nuget package version 0.13.0 has been released

**Comment by Jericho** [comment]
@Gekctek off topic question: I am curious what you use to parse the webhook requests and if you think it would be useful to add webhook parsing feature to the StrongGrid library?

**Comment by Gekctek** [comment]
https://github.com/edjCase/SendGrid.WebHooks is what I use to parse it
right now. But I look at the RawProperties property in WebHookEvent and
parse it out manually. I think it would be helpful

**Comment by Jericho** [comment]
Ok, I'll create a new ticket to track this new feature. Feel free to comment if you want to suggest he w it should work.

Actually, now that I think about it, I'll create two tickets: one for even webhook parsing and one for inbound email parsing.
